// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: ble_profiles.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
export const protobufPackage = "zmk.ble_profiles";
export var Transport;
(function (Transport) {
    Transport[Transport["TRANSPORT_NONE"] = 0] = "TRANSPORT_NONE";
    Transport[Transport["TRANSPORT_USB"] = 1] = "TRANSPORT_USB";
    Transport[Transport["TRANSPORT_BLE"] = 2] = "TRANSPORT_BLE";
    Transport[Transport["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(Transport || (Transport = {}));
export function transportFromJSON(object) {
    switch (object) {
        case 0:
        case "TRANSPORT_NONE":
            return Transport.TRANSPORT_NONE;
        case 1:
        case "TRANSPORT_USB":
            return Transport.TRANSPORT_USB;
        case 2:
        case "TRANSPORT_BLE":
            return Transport.TRANSPORT_BLE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return Transport.UNRECOGNIZED;
    }
}
export function transportToJSON(object) {
    switch (object) {
        case Transport.TRANSPORT_NONE:
            return "TRANSPORT_NONE";
        case Transport.TRANSPORT_USB:
            return "TRANSPORT_USB";
        case Transport.TRANSPORT_BLE:
            return "TRANSPORT_BLE";
        case Transport.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var MutationError;
(function (MutationError) {
    MutationError[MutationError["MUTATION_OK"] = 0] = "MUTATION_OK";
    MutationError[MutationError["MUTATION_INVALID_INDEX"] = 1] = "MUTATION_INVALID_INDEX";
    MutationError[MutationError["MUTATION_INVALID_NAME"] = 2] = "MUTATION_INVALID_NAME";
    MutationError[MutationError["MUTATION_INVALID_TRANSPORT"] = 3] = "MUTATION_INVALID_TRANSPORT";
    MutationError[MutationError["MUTATION_SAVE_FAILED"] = 4] = "MUTATION_SAVE_FAILED";
    MutationError[MutationError["MUTATION_APPLY_FAILED"] = 5] = "MUTATION_APPLY_FAILED";
    MutationError[MutationError["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(MutationError || (MutationError = {}));
export function mutationErrorFromJSON(object) {
    switch (object) {
        case 0:
        case "MUTATION_OK":
            return MutationError.MUTATION_OK;
        case 1:
        case "MUTATION_INVALID_INDEX":
            return MutationError.MUTATION_INVALID_INDEX;
        case 2:
        case "MUTATION_INVALID_NAME":
            return MutationError.MUTATION_INVALID_NAME;
        case 3:
        case "MUTATION_INVALID_TRANSPORT":
            return MutationError.MUTATION_INVALID_TRANSPORT;
        case 4:
        case "MUTATION_SAVE_FAILED":
            return MutationError.MUTATION_SAVE_FAILED;
        case 5:
        case "MUTATION_APPLY_FAILED":
            return MutationError.MUTATION_APPLY_FAILED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return MutationError.UNRECOGNIZED;
    }
}
export function mutationErrorToJSON(object) {
    switch (object) {
        case MutationError.MUTATION_OK:
            return "MUTATION_OK";
        case MutationError.MUTATION_INVALID_INDEX:
            return "MUTATION_INVALID_INDEX";
        case MutationError.MUTATION_INVALID_NAME:
            return "MUTATION_INVALID_NAME";
        case MutationError.MUTATION_INVALID_TRANSPORT:
            return "MUTATION_INVALID_TRANSPORT";
        case MutationError.MUTATION_SAVE_FAILED:
            return "MUTATION_SAVE_FAILED";
        case MutationError.MUTATION_APPLY_FAILED:
            return "MUTATION_APPLY_FAILED";
        case MutationError.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseRequest() {
    return {
        getProfiles: undefined,
        setName: undefined,
        selectProfile: undefined,
        unpairProfile: undefined,
        setPreferredTransport: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getProfiles !== undefined) {
            writer.uint32(8).bool(message.getProfiles);
        }
        if (message.setName !== undefined) {
            SetNameRequest.encode(message.setName, writer.uint32(18).fork()).ldelim();
        }
        if (message.selectProfile !== undefined) {
            SelectProfileRequest.encode(message.selectProfile, writer.uint32(26).fork()).ldelim();
        }
        if (message.unpairProfile !== undefined) {
            UnpairProfileRequest.encode(message.unpairProfile, writer.uint32(34).fork()).ldelim();
        }
        if (message.setPreferredTransport !== undefined) {
            SetPreferredTransportRequest.encode(message.setPreferredTransport, writer.uint32(42).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.getProfiles = reader.bool();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setName = SetNameRequest.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.selectProfile = SelectProfileRequest.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.unpairProfile = UnpairProfileRequest.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.setPreferredTransport = SetPreferredTransportRequest.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getProfiles: isSet(object.getProfiles) ? globalThis.Boolean(object.getProfiles) : undefined,
            setName: isSet(object.setName) ? SetNameRequest.fromJSON(object.setName) : undefined,
            selectProfile: isSet(object.selectProfile) ? SelectProfileRequest.fromJSON(object.selectProfile) : undefined,
            unpairProfile: isSet(object.unpairProfile) ? UnpairProfileRequest.fromJSON(object.unpairProfile) : undefined,
            setPreferredTransport: isSet(object.setPreferredTransport)
                ? SetPreferredTransportRequest.fromJSON(object.setPreferredTransport)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getProfiles !== undefined) {
            obj.getProfiles = message.getProfiles;
        }
        if (message.setName !== undefined) {
            obj.setName = SetNameRequest.toJSON(message.setName);
        }
        if (message.selectProfile !== undefined) {
            obj.selectProfile = SelectProfileRequest.toJSON(message.selectProfile);
        }
        if (message.unpairProfile !== undefined) {
            obj.unpairProfile = UnpairProfileRequest.toJSON(message.unpairProfile);
        }
        if (message.setPreferredTransport !== undefined) {
            obj.setPreferredTransport = SetPreferredTransportRequest.toJSON(message.setPreferredTransport);
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.getProfiles = object.getProfiles ?? undefined;
        message.setName = (object.setName !== undefined && object.setName !== null)
            ? SetNameRequest.fromPartial(object.setName)
            : undefined;
        message.selectProfile = (object.selectProfile !== undefined && object.selectProfile !== null)
            ? SelectProfileRequest.fromPartial(object.selectProfile)
            : undefined;
        message.unpairProfile = (object.unpairProfile !== undefined && object.unpairProfile !== null)
            ? UnpairProfileRequest.fromPartial(object.unpairProfile)
            : undefined;
        message.setPreferredTransport =
            (object.setPreferredTransport !== undefined && object.setPreferredTransport !== null)
                ? SetPreferredTransportRequest.fromPartial(object.setPreferredTransport)
                : undefined;
        return message;
    },
};
function createBaseResponse() {
    return {
        getProfiles: undefined,
        setName: undefined,
        selectProfile: undefined,
        unpairProfile: undefined,
        setPreferredTransport: undefined,
    };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getProfiles !== undefined) {
            GetProfilesResponse.encode(message.getProfiles, writer.uint32(10).fork()).ldelim();
        }
        if (message.setName !== undefined) {
            MutationResponse.encode(message.setName, writer.uint32(18).fork()).ldelim();
        }
        if (message.selectProfile !== undefined) {
            MutationResponse.encode(message.selectProfile, writer.uint32(26).fork()).ldelim();
        }
        if (message.unpairProfile !== undefined) {
            MutationResponse.encode(message.unpairProfile, writer.uint32(34).fork()).ldelim();
        }
        if (message.setPreferredTransport !== undefined) {
            MutationResponse.encode(message.setPreferredTransport, writer.uint32(42).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.getProfiles = GetProfilesResponse.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setName = MutationResponse.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.selectProfile = MutationResponse.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.unpairProfile = MutationResponse.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.setPreferredTransport = MutationResponse.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getProfiles: isSet(object.getProfiles) ? GetProfilesResponse.fromJSON(object.getProfiles) : undefined,
            setName: isSet(object.setName) ? MutationResponse.fromJSON(object.setName) : undefined,
            selectProfile: isSet(object.selectProfile) ? MutationResponse.fromJSON(object.selectProfile) : undefined,
            unpairProfile: isSet(object.unpairProfile) ? MutationResponse.fromJSON(object.unpairProfile) : undefined,
            setPreferredTransport: isSet(object.setPreferredTransport)
                ? MutationResponse.fromJSON(object.setPreferredTransport)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getProfiles !== undefined) {
            obj.getProfiles = GetProfilesResponse.toJSON(message.getProfiles);
        }
        if (message.setName !== undefined) {
            obj.setName = MutationResponse.toJSON(message.setName);
        }
        if (message.selectProfile !== undefined) {
            obj.selectProfile = MutationResponse.toJSON(message.selectProfile);
        }
        if (message.unpairProfile !== undefined) {
            obj.unpairProfile = MutationResponse.toJSON(message.unpairProfile);
        }
        if (message.setPreferredTransport !== undefined) {
            obj.setPreferredTransport = MutationResponse.toJSON(message.setPreferredTransport);
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.getProfiles = (object.getProfiles !== undefined && object.getProfiles !== null)
            ? GetProfilesResponse.fromPartial(object.getProfiles)
            : undefined;
        message.setName = (object.setName !== undefined && object.setName !== null)
            ? MutationResponse.fromPartial(object.setName)
            : undefined;
        message.selectProfile = (object.selectProfile !== undefined && object.selectProfile !== null)
            ? MutationResponse.fromPartial(object.selectProfile)
            : undefined;
        message.unpairProfile = (object.unpairProfile !== undefined && object.unpairProfile !== null)
            ? MutationResponse.fromPartial(object.unpairProfile)
            : undefined;
        message.setPreferredTransport =
            (object.setPreferredTransport !== undefined && object.setPreferredTransport !== null)
                ? MutationResponse.fromPartial(object.setPreferredTransport)
                : undefined;
        return message;
    },
};
function createBaseProfile() {
    return { index: 0, name: "", address: "", open: false, connected: false, active: false };
}
export const Profile = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.index !== 0) {
            writer.uint32(8).uint32(message.index);
        }
        if (message.name !== "") {
            writer.uint32(18).string(message.name);
        }
        if (message.address !== "") {
            writer.uint32(26).string(message.address);
        }
        if (message.open !== false) {
            writer.uint32(32).bool(message.open);
        }
        if (message.connected !== false) {
            writer.uint32(40).bool(message.connected);
        }
        if (message.active !== false) {
            writer.uint32(48).bool(message.active);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseProfile();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.index = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.address = reader.string();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.open = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.connected = reader.bool();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.active = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            index: isSet(object.index) ? globalThis.Number(object.index) : 0,
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            address: isSet(object.address) ? globalThis.String(object.address) : "",
            open: isSet(object.open) ? globalThis.Boolean(object.open) : false,
            connected: isSet(object.connected) ? globalThis.Boolean(object.connected) : false,
            active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.index !== 0) {
            obj.index = Math.round(message.index);
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.address !== "") {
            obj.address = message.address;
        }
        if (message.open !== false) {
            obj.open = message.open;
        }
        if (message.connected !== false) {
            obj.connected = message.connected;
        }
        if (message.active !== false) {
            obj.active = message.active;
        }
        return obj;
    },
    create(base) {
        return Profile.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseProfile();
        message.index = object.index ?? 0;
        message.name = object.name ?? "";
        message.address = object.address ?? "";
        message.open = object.open ?? false;
        message.connected = object.connected ?? false;
        message.active = object.active ?? false;
        return message;
    },
};
function createBaseGetProfilesResponse() {
    return { slotCount: 0, profiles: [], activeIndex: 0, preferredTransport: 0, selectedTransport: 0 };
}
export const GetProfilesResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.slotCount !== 0) {
            writer.uint32(8).uint32(message.slotCount);
        }
        for (const v of message.profiles) {
            Profile.encode(v, writer.uint32(18).fork()).ldelim();
        }
        if (message.activeIndex !== 0) {
            writer.uint32(24).uint32(message.activeIndex);
        }
        if (message.preferredTransport !== 0) {
            writer.uint32(32).int32(message.preferredTransport);
        }
        if (message.selectedTransport !== 0) {
            writer.uint32(40).int32(message.selectedTransport);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetProfilesResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.slotCount = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.profiles.push(Profile.decode(reader, reader.uint32()));
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.activeIndex = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.preferredTransport = reader.int32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.selectedTransport = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            slotCount: isSet(object.slotCount) ? globalThis.Number(object.slotCount) : 0,
            profiles: globalThis.Array.isArray(object?.profiles) ? object.profiles.map((e) => Profile.fromJSON(e)) : [],
            activeIndex: isSet(object.activeIndex) ? globalThis.Number(object.activeIndex) : 0,
            preferredTransport: isSet(object.preferredTransport) ? transportFromJSON(object.preferredTransport) : 0,
            selectedTransport: isSet(object.selectedTransport) ? transportFromJSON(object.selectedTransport) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.slotCount !== 0) {
            obj.slotCount = Math.round(message.slotCount);
        }
        if (message.profiles?.length) {
            obj.profiles = message.profiles.map((e) => Profile.toJSON(e));
        }
        if (message.activeIndex !== 0) {
            obj.activeIndex = Math.round(message.activeIndex);
        }
        if (message.preferredTransport !== 0) {
            obj.preferredTransport = transportToJSON(message.preferredTransport);
        }
        if (message.selectedTransport !== 0) {
            obj.selectedTransport = transportToJSON(message.selectedTransport);
        }
        return obj;
    },
    create(base) {
        return GetProfilesResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetProfilesResponse();
        message.slotCount = object.slotCount ?? 0;
        message.profiles = object.profiles?.map((e) => Profile.fromPartial(e)) || [];
        message.activeIndex = object.activeIndex ?? 0;
        message.preferredTransport = object.preferredTransport ?? 0;
        message.selectedTransport = object.selectedTransport ?? 0;
        return message;
    },
};
function createBaseSetNameRequest() {
    return { index: 0, nameUtf8: new Uint8Array(0) };
}
export const SetNameRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.index !== 0) {
            writer.uint32(8).uint32(message.index);
        }
        if (message.nameUtf8.length !== 0) {
            writer.uint32(18).bytes(message.nameUtf8);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetNameRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.index = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.nameUtf8 = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            index: isSet(object.index) ? globalThis.Number(object.index) : 0,
            nameUtf8: isSet(object.nameUtf8) ? bytesFromBase64(object.nameUtf8) : new Uint8Array(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.index !== 0) {
            obj.index = Math.round(message.index);
        }
        if (message.nameUtf8.length !== 0) {
            obj.nameUtf8 = base64FromBytes(message.nameUtf8);
        }
        return obj;
    },
    create(base) {
        return SetNameRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetNameRequest();
        message.index = object.index ?? 0;
        message.nameUtf8 = object.nameUtf8 ?? new Uint8Array(0);
        return message;
    },
};
function createBaseSelectProfileRequest() {
    return { index: 0 };
}
export const SelectProfileRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.index !== 0) {
            writer.uint32(8).uint32(message.index);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSelectProfileRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.index = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { index: isSet(object.index) ? globalThis.Number(object.index) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.index !== 0) {
            obj.index = Math.round(message.index);
        }
        return obj;
    },
    create(base) {
        return SelectProfileRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSelectProfileRequest();
        message.index = object.index ?? 0;
        return message;
    },
};
function createBaseUnpairProfileRequest() {
    return { index: 0 };
}
export const UnpairProfileRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.index !== 0) {
            writer.uint32(8).uint32(message.index);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUnpairProfileRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.index = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { index: isSet(object.index) ? globalThis.Number(object.index) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.index !== 0) {
            obj.index = Math.round(message.index);
        }
        return obj;
    },
    create(base) {
        return UnpairProfileRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUnpairProfileRequest();
        message.index = object.index ?? 0;
        return message;
    },
};
function createBaseSetPreferredTransportRequest() {
    return { transport: 0 };
}
export const SetPreferredTransportRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.transport !== 0) {
            writer.uint32(8).int32(message.transport);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetPreferredTransportRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.transport = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { transport: isSet(object.transport) ? transportFromJSON(object.transport) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.transport !== 0) {
            obj.transport = transportToJSON(message.transport);
        }
        return obj;
    },
    create(base) {
        return SetPreferredTransportRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetPreferredTransportRequest();
        message.transport = object.transport ?? 0;
        return message;
    },
};
function createBaseMutationResponse() {
    return { error: 0 };
}
export const MutationResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.error !== 0) {
            writer.uint32(8).int32(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMutationResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.error = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { error: isSet(object.error) ? mutationErrorFromJSON(object.error) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.error !== 0) {
            obj.error = mutationErrorToJSON(message.error);
        }
        return obj;
    },
    create(base) {
        return MutationResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMutationResponse();
        message.error = object.error ?? 0;
        return message;
    },
};
function bytesFromBase64(b64) {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
        arr[i] = bin.charCodeAt(i);
    }
    return arr;
}
function base64FromBytes(arr) {
    const bin = [];
    arr.forEach((byte) => {
        bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
}
function isSet(value) {
    return value !== null && value !== undefined;
}
