// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: combos.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";
export const protobufPackage = "zmk.combos";
export var ComboSource;
(function (ComboSource) {
    ComboSource[ComboSource["COMBO_SOURCE_STOCK"] = 0] = "COMBO_SOURCE_STOCK";
    ComboSource[ComboSource["COMBO_SOURCE_USER"] = 1] = "COMBO_SOURCE_USER";
    ComboSource[ComboSource["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ComboSource || (ComboSource = {}));
export function comboSourceFromJSON(object) {
    switch (object) {
        case 0:
        case "COMBO_SOURCE_STOCK":
            return ComboSource.COMBO_SOURCE_STOCK;
        case 1:
        case "COMBO_SOURCE_USER":
            return ComboSource.COMBO_SOURCE_USER;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ComboSource.UNRECOGNIZED;
    }
}
export function comboSourceToJSON(object) {
    switch (object) {
        case ComboSource.COMBO_SOURCE_STOCK:
            return "COMBO_SOURCE_STOCK";
        case ComboSource.COMBO_SOURCE_USER:
            return "COMBO_SOURCE_USER";
        case ComboSource.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SetComboErrorCode;
(function (SetComboErrorCode) {
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_OK"] = 0] = "SET_COMBO_ERR_OK";
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_GENERIC"] = 1] = "SET_COMBO_ERR_GENERIC";
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_INVALID_SLOT"] = 2] = "SET_COMBO_ERR_INVALID_SLOT";
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_INVALID_BEHAVIOR"] = 3] = "SET_COMBO_ERR_INVALID_BEHAVIOR";
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_INVALID_PARAMETERS"] = 4] = "SET_COMBO_ERR_INVALID_PARAMETERS";
    SetComboErrorCode[SetComboErrorCode["SET_COMBO_ERR_BUSY"] = 5] = "SET_COMBO_ERR_BUSY";
    SetComboErrorCode[SetComboErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SetComboErrorCode || (SetComboErrorCode = {}));
export function setComboErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SET_COMBO_ERR_OK":
            return SetComboErrorCode.SET_COMBO_ERR_OK;
        case 1:
        case "SET_COMBO_ERR_GENERIC":
            return SetComboErrorCode.SET_COMBO_ERR_GENERIC;
        case 2:
        case "SET_COMBO_ERR_INVALID_SLOT":
            return SetComboErrorCode.SET_COMBO_ERR_INVALID_SLOT;
        case 3:
        case "SET_COMBO_ERR_INVALID_BEHAVIOR":
            return SetComboErrorCode.SET_COMBO_ERR_INVALID_BEHAVIOR;
        case 4:
        case "SET_COMBO_ERR_INVALID_PARAMETERS":
            return SetComboErrorCode.SET_COMBO_ERR_INVALID_PARAMETERS;
        case 5:
        case "SET_COMBO_ERR_BUSY":
            return SetComboErrorCode.SET_COMBO_ERR_BUSY;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SetComboErrorCode.UNRECOGNIZED;
    }
}
export function setComboErrorCodeToJSON(object) {
    switch (object) {
        case SetComboErrorCode.SET_COMBO_ERR_OK:
            return "SET_COMBO_ERR_OK";
        case SetComboErrorCode.SET_COMBO_ERR_GENERIC:
            return "SET_COMBO_ERR_GENERIC";
        case SetComboErrorCode.SET_COMBO_ERR_INVALID_SLOT:
            return "SET_COMBO_ERR_INVALID_SLOT";
        case SetComboErrorCode.SET_COMBO_ERR_INVALID_BEHAVIOR:
            return "SET_COMBO_ERR_INVALID_BEHAVIOR";
        case SetComboErrorCode.SET_COMBO_ERR_INVALID_PARAMETERS:
            return "SET_COMBO_ERR_INVALID_PARAMETERS";
        case SetComboErrorCode.SET_COMBO_ERR_BUSY:
            return "SET_COMBO_ERR_BUSY";
        case SetComboErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SaveChangesErrorCode;
(function (SaveChangesErrorCode) {
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_OK"] = 0] = "SAVE_CHANGES_ERR_OK";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_GENERIC"] = 1] = "SAVE_CHANGES_ERR_GENERIC";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NOT_SUPPORTED"] = 2] = "SAVE_CHANGES_ERR_NOT_SUPPORTED";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NO_SPACE"] = 3] = "SAVE_CHANGES_ERR_NO_SPACE";
    SaveChangesErrorCode[SaveChangesErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SaveChangesErrorCode || (SaveChangesErrorCode = {}));
export function saveChangesErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SAVE_CHANGES_ERR_OK":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_OK;
        case 1:
        case "SAVE_CHANGES_ERR_GENERIC":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC;
        case 2:
        case "SAVE_CHANGES_ERR_NOT_SUPPORTED":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED;
        case 3:
        case "SAVE_CHANGES_ERR_NO_SPACE":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SaveChangesErrorCode.UNRECOGNIZED;
    }
}
export function saveChangesErrorCodeToJSON(object) {
    switch (object) {
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_OK:
            return "SAVE_CHANGES_ERR_OK";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC:
            return "SAVE_CHANGES_ERR_GENERIC";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED:
            return "SAVE_CHANGES_ERR_NOT_SUPPORTED";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE:
            return "SAVE_CHANGES_ERR_NO_SPACE";
        case SaveChangesErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseRequest() {
    return {
        getComboState: undefined,
        setCombo: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getComboState !== undefined) {
            writer.uint32(8).bool(message.getComboState);
        }
        if (message.setCombo !== undefined) {
            SetComboRequest.encode(message.setCombo, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            writer.uint32(32).bool(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.getComboState = reader.bool();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setCombo = SetComboRequest.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.saveChanges = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getComboState: isSet(object.getComboState) ? globalThis.Boolean(object.getComboState) : undefined,
            setCombo: isSet(object.setCombo) ? SetComboRequest.fromJSON(object.setCombo) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? globalThis.Boolean(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getComboState !== undefined) {
            obj.getComboState = message.getComboState;
        }
        if (message.setCombo !== undefined) {
            obj.setCombo = SetComboRequest.toJSON(message.setCombo);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = message.saveChanges;
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.getComboState = object.getComboState ?? undefined;
        message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
            ? SetComboRequest.fromPartial(object.setCombo)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = object.saveChanges ?? undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseResponse() {
    return {
        getComboState: undefined,
        setCombo: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getComboState !== undefined) {
            ComboState.encode(message.getComboState, writer.uint32(10).fork()).ldelim();
        }
        if (message.setCombo !== undefined) {
            SetComboResponse.encode(message.setCombo, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            SaveChangesResponse.encode(message.saveChanges, writer.uint32(34).fork()).ldelim();
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.getComboState = ComboState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setCombo = SetComboResponse.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getComboState: isSet(object.getComboState) ? ComboState.fromJSON(object.getComboState) : undefined,
            setCombo: isSet(object.setCombo) ? SetComboResponse.fromJSON(object.setCombo) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getComboState !== undefined) {
            obj.getComboState = ComboState.toJSON(message.getComboState);
        }
        if (message.setCombo !== undefined) {
            obj.setCombo = SetComboResponse.toJSON(message.setCombo);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.getComboState = (object.getComboState !== undefined && object.getComboState !== null)
            ? ComboState.fromPartial(object.getComboState)
            : undefined;
        message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
            ? SetComboResponse.fromPartial(object.setCombo)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
            ? SaveChangesResponse.fromPartial(object.saveChanges)
            : undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseNotification() {
    return { comboStateChanged: undefined, unsavedChangesStatusChanged: undefined };
}
export const Notification = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.comboStateChanged !== undefined) {
            ComboState.encode(message.comboStateChanged, writer.uint32(10).fork()).ldelim();
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            writer.uint32(16).bool(message.unsavedChangesStatusChanged);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNotification();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.comboStateChanged = ComboState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.unsavedChangesStatusChanged = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            comboStateChanged: isSet(object.comboStateChanged) ? ComboState.fromJSON(object.comboStateChanged) : undefined,
            unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
                ? globalThis.Boolean(object.unsavedChangesStatusChanged)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.comboStateChanged !== undefined) {
            obj.comboStateChanged = ComboState.toJSON(message.comboStateChanged);
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
        }
        return obj;
    },
    create(base) {
        return Notification.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNotification();
        message.comboStateChanged = (object.comboStateChanged !== undefined && object.comboStateChanged !== null)
            ? ComboState.fromPartial(object.comboStateChanged)
            : undefined;
        message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
        return message;
    },
};
function createBaseComboState() {
    return { schemaVersion: 0, maxCombos: 0, maxKeysPerCombo: 0, combos: [], dirty: false };
}
export const ComboState = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.schemaVersion !== 0) {
            writer.uint32(8).uint32(message.schemaVersion);
        }
        if (message.maxCombos !== 0) {
            writer.uint32(16).uint32(message.maxCombos);
        }
        if (message.maxKeysPerCombo !== 0) {
            writer.uint32(24).uint32(message.maxKeysPerCombo);
        }
        for (const v of message.combos) {
            Combo.encode(v, writer.uint32(34).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(40).bool(message.dirty);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseComboState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.schemaVersion = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.maxCombos = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.maxKeysPerCombo = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.combos.push(Combo.decode(reader, reader.uint32()));
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            schemaVersion: isSet(object.schemaVersion) ? globalThis.Number(object.schemaVersion) : 0,
            maxCombos: isSet(object.maxCombos) ? globalThis.Number(object.maxCombos) : 0,
            maxKeysPerCombo: isSet(object.maxKeysPerCombo) ? globalThis.Number(object.maxKeysPerCombo) : 0,
            combos: globalThis.Array.isArray(object?.combos) ? object.combos.map((e) => Combo.fromJSON(e)) : [],
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.schemaVersion !== 0) {
            obj.schemaVersion = Math.round(message.schemaVersion);
        }
        if (message.maxCombos !== 0) {
            obj.maxCombos = Math.round(message.maxCombos);
        }
        if (message.maxKeysPerCombo !== 0) {
            obj.maxKeysPerCombo = Math.round(message.maxKeysPerCombo);
        }
        if (message.combos?.length) {
            obj.combos = message.combos.map((e) => Combo.toJSON(e));
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        return obj;
    },
    create(base) {
        return ComboState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseComboState();
        message.schemaVersion = object.schemaVersion ?? 0;
        message.maxCombos = object.maxCombos ?? 0;
        message.maxKeysPerCombo = object.maxKeysPerCombo ?? 0;
        message.combos = object.combos?.map((e) => Combo.fromPartial(e)) || [];
        message.dirty = object.dirty ?? false;
        return message;
    },
};
function createBaseCombo() {
    return {
        comboId: "",
        slotIndex: 0,
        source: 0,
        enabled: false,
        binding: undefined,
        keyPositions: [],
        layers: [],
        timeoutMs: 0,
        requirePriorIdleMs: 0,
        slowRelease: false,
        dirty: false,
    };
}
export const Combo = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.comboId !== "") {
            writer.uint32(10).string(message.comboId);
        }
        if (message.slotIndex !== 0) {
            writer.uint32(16).uint32(message.slotIndex);
        }
        if (message.source !== 0) {
            writer.uint32(24).int32(message.source);
        }
        if (message.enabled !== false) {
            writer.uint32(32).bool(message.enabled);
        }
        if (message.binding !== undefined) {
            BehaviorBinding.encode(message.binding, writer.uint32(42).fork()).ldelim();
        }
        writer.uint32(50).fork();
        for (const v of message.keyPositions) {
            writer.uint32(v);
        }
        writer.ldelim();
        writer.uint32(58).fork();
        for (const v of message.layers) {
            writer.uint32(v);
        }
        writer.ldelim();
        if (message.timeoutMs !== 0) {
            writer.uint32(64).uint32(message.timeoutMs);
        }
        if (message.requirePriorIdleMs !== 0) {
            writer.uint32(72).sint32(message.requirePriorIdleMs);
        }
        if (message.slowRelease !== false) {
            writer.uint32(80).bool(message.slowRelease);
        }
        if (message.dirty !== false) {
            writer.uint32(88).bool(message.dirty);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCombo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.comboId = reader.string();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.slotIndex = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.source = reader.int32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.enabled = reader.bool();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.binding = BehaviorBinding.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag === 48) {
                        message.keyPositions.push(reader.uint32());
                        continue;
                    }
                    if (tag === 50) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.keyPositions.push(reader.uint32());
                        }
                        continue;
                    }
                    break;
                case 7:
                    if (tag === 56) {
                        message.layers.push(reader.uint32());
                        continue;
                    }
                    if (tag === 58) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.layers.push(reader.uint32());
                        }
                        continue;
                    }
                    break;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.timeoutMs = reader.uint32();
                    continue;
                case 9:
                    if (tag !== 72) {
                        break;
                    }
                    message.requirePriorIdleMs = reader.sint32();
                    continue;
                case 10:
                    if (tag !== 80) {
                        break;
                    }
                    message.slowRelease = reader.bool();
                    continue;
                case 11:
                    if (tag !== 88) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            comboId: isSet(object.comboId) ? globalThis.String(object.comboId) : "",
            slotIndex: isSet(object.slotIndex) ? globalThis.Number(object.slotIndex) : 0,
            source: isSet(object.source) ? comboSourceFromJSON(object.source) : 0,
            enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
            binding: isSet(object.binding) ? BehaviorBinding.fromJSON(object.binding) : undefined,
            keyPositions: globalThis.Array.isArray(object?.keyPositions)
                ? object.keyPositions.map((e) => globalThis.Number(e))
                : [],
            layers: globalThis.Array.isArray(object?.layers) ? object.layers.map((e) => globalThis.Number(e)) : [],
            timeoutMs: isSet(object.timeoutMs) ? globalThis.Number(object.timeoutMs) : 0,
            requirePriorIdleMs: isSet(object.requirePriorIdleMs) ? globalThis.Number(object.requirePriorIdleMs) : 0,
            slowRelease: isSet(object.slowRelease) ? globalThis.Boolean(object.slowRelease) : false,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.comboId !== "") {
            obj.comboId = message.comboId;
        }
        if (message.slotIndex !== 0) {
            obj.slotIndex = Math.round(message.slotIndex);
        }
        if (message.source !== 0) {
            obj.source = comboSourceToJSON(message.source);
        }
        if (message.enabled !== false) {
            obj.enabled = message.enabled;
        }
        if (message.binding !== undefined) {
            obj.binding = BehaviorBinding.toJSON(message.binding);
        }
        if (message.keyPositions?.length) {
            obj.keyPositions = message.keyPositions.map((e) => Math.round(e));
        }
        if (message.layers?.length) {
            obj.layers = message.layers.map((e) => Math.round(e));
        }
        if (message.timeoutMs !== 0) {
            obj.timeoutMs = Math.round(message.timeoutMs);
        }
        if (message.requirePriorIdleMs !== 0) {
            obj.requirePriorIdleMs = Math.round(message.requirePriorIdleMs);
        }
        if (message.slowRelease !== false) {
            obj.slowRelease = message.slowRelease;
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        return obj;
    },
    create(base) {
        return Combo.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCombo();
        message.comboId = object.comboId ?? "";
        message.slotIndex = object.slotIndex ?? 0;
        message.source = object.source ?? 0;
        message.enabled = object.enabled ?? false;
        message.binding = (object.binding !== undefined && object.binding !== null)
            ? BehaviorBinding.fromPartial(object.binding)
            : undefined;
        message.keyPositions = object.keyPositions?.map((e) => e) || [];
        message.layers = object.layers?.map((e) => e) || [];
        message.timeoutMs = object.timeoutMs ?? 0;
        message.requirePriorIdleMs = object.requirePriorIdleMs ?? 0;
        message.slowRelease = object.slowRelease ?? false;
        message.dirty = object.dirty ?? false;
        return message;
    },
};
function createBaseSetComboRequest() {
    return { combo: undefined };
}
export const SetComboRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.combo !== undefined) {
            Combo.encode(message.combo, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetComboRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.combo = Combo.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.combo !== undefined) {
            obj.combo = Combo.toJSON(message.combo);
        }
        return obj;
    },
    create(base) {
        return SetComboRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetComboRequest();
        message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
        return message;
    },
};
function createBaseSetComboResponse() {
    return { ok: undefined, err: undefined };
}
export const SetComboResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            SetComboOk.encode(message.ok, writer.uint32(10).fork()).ldelim();
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetComboResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.ok = SetComboOk.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? SetComboOk.fromJSON(object.ok) : undefined,
            err: isSet(object.err) ? setComboErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = SetComboOk.toJSON(message.ok);
        }
        if (message.err !== undefined) {
            obj.err = setComboErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SetComboResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetComboResponse();
        message.ok = (object.ok !== undefined && object.ok !== null) ? SetComboOk.fromPartial(object.ok) : undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function createBaseSetComboOk() {
    return { combo: undefined, dirty: false };
}
export const SetComboOk = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.combo !== undefined) {
            Combo.encode(message.combo, writer.uint32(10).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(16).bool(message.dirty);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetComboOk();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.combo = Combo.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.combo !== undefined) {
            obj.combo = Combo.toJSON(message.combo);
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        return obj;
    },
    create(base) {
        return SetComboOk.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetComboOk();
        message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
        message.dirty = object.dirty ?? false;
        return message;
    },
};
function createBaseSaveChangesResponse() {
    return { ok: undefined, err: undefined };
}
export const SaveChangesResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            writer.uint32(8).bool(message.ok);
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveChangesResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.ok = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
            err: isSet(object.err) ? saveChangesErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = message.ok;
        }
        if (message.err !== undefined) {
            obj.err = saveChangesErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SaveChangesResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveChangesResponse();
        message.ok = object.ok ?? undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
