// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: macros.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";
export const protobufPackage = "zmk.macros";
export var MacroStepAction;
(function (MacroStepAction) {
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_UNSPECIFIED"] = 0] = "MACRO_STEP_ACTION_UNSPECIFIED";
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_TAP"] = 1] = "MACRO_STEP_ACTION_TAP";
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_PRESS"] = 2] = "MACRO_STEP_ACTION_PRESS";
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_RELEASE"] = 3] = "MACRO_STEP_ACTION_RELEASE";
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_WAIT"] = 4] = "MACRO_STEP_ACTION_WAIT";
    MacroStepAction[MacroStepAction["MACRO_STEP_ACTION_TEXT"] = 5] = "MACRO_STEP_ACTION_TEXT";
    MacroStepAction[MacroStepAction["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(MacroStepAction || (MacroStepAction = {}));
export function macroStepActionFromJSON(object) {
    switch (object) {
        case 0:
        case "MACRO_STEP_ACTION_UNSPECIFIED":
            return MacroStepAction.MACRO_STEP_ACTION_UNSPECIFIED;
        case 1:
        case "MACRO_STEP_ACTION_TAP":
            return MacroStepAction.MACRO_STEP_ACTION_TAP;
        case 2:
        case "MACRO_STEP_ACTION_PRESS":
            return MacroStepAction.MACRO_STEP_ACTION_PRESS;
        case 3:
        case "MACRO_STEP_ACTION_RELEASE":
            return MacroStepAction.MACRO_STEP_ACTION_RELEASE;
        case 4:
        case "MACRO_STEP_ACTION_WAIT":
            return MacroStepAction.MACRO_STEP_ACTION_WAIT;
        case 5:
        case "MACRO_STEP_ACTION_TEXT":
            return MacroStepAction.MACRO_STEP_ACTION_TEXT;
        case -1:
        case "UNRECOGNIZED":
        default:
            return MacroStepAction.UNRECOGNIZED;
    }
}
export function macroStepActionToJSON(object) {
    switch (object) {
        case MacroStepAction.MACRO_STEP_ACTION_UNSPECIFIED:
            return "MACRO_STEP_ACTION_UNSPECIFIED";
        case MacroStepAction.MACRO_STEP_ACTION_TAP:
            return "MACRO_STEP_ACTION_TAP";
        case MacroStepAction.MACRO_STEP_ACTION_PRESS:
            return "MACRO_STEP_ACTION_PRESS";
        case MacroStepAction.MACRO_STEP_ACTION_RELEASE:
            return "MACRO_STEP_ACTION_RELEASE";
        case MacroStepAction.MACRO_STEP_ACTION_WAIT:
            return "MACRO_STEP_ACTION_WAIT";
        case MacroStepAction.MACRO_STEP_ACTION_TEXT:
            return "MACRO_STEP_ACTION_TEXT";
        case MacroStepAction.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SetMacroErrorCode;
(function (SetMacroErrorCode) {
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_OK"] = 0] = "SET_MACRO_ERR_OK";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_GENERIC"] = 1] = "SET_MACRO_ERR_GENERIC";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_INVALID_SLOT"] = 2] = "SET_MACRO_ERR_INVALID_SLOT";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_INVALID_NAME"] = 3] = "SET_MACRO_ERR_INVALID_NAME";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_INVALID_STEP"] = 4] = "SET_MACRO_ERR_INVALID_STEP";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_INVALID_BEHAVIOR"] = 5] = "SET_MACRO_ERR_INVALID_BEHAVIOR";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_INVALID_PARAMETERS"] = 6] = "SET_MACRO_ERR_INVALID_PARAMETERS";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_BUSY"] = 7] = "SET_MACRO_ERR_BUSY";
    SetMacroErrorCode[SetMacroErrorCode["SET_MACRO_ERR_NO_SPACE"] = 8] = "SET_MACRO_ERR_NO_SPACE";
    SetMacroErrorCode[SetMacroErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SetMacroErrorCode || (SetMacroErrorCode = {}));
export function setMacroErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SET_MACRO_ERR_OK":
            return SetMacroErrorCode.SET_MACRO_ERR_OK;
        case 1:
        case "SET_MACRO_ERR_GENERIC":
            return SetMacroErrorCode.SET_MACRO_ERR_GENERIC;
        case 2:
        case "SET_MACRO_ERR_INVALID_SLOT":
            return SetMacroErrorCode.SET_MACRO_ERR_INVALID_SLOT;
        case 3:
        case "SET_MACRO_ERR_INVALID_NAME":
            return SetMacroErrorCode.SET_MACRO_ERR_INVALID_NAME;
        case 4:
        case "SET_MACRO_ERR_INVALID_STEP":
            return SetMacroErrorCode.SET_MACRO_ERR_INVALID_STEP;
        case 5:
        case "SET_MACRO_ERR_INVALID_BEHAVIOR":
            return SetMacroErrorCode.SET_MACRO_ERR_INVALID_BEHAVIOR;
        case 6:
        case "SET_MACRO_ERR_INVALID_PARAMETERS":
            return SetMacroErrorCode.SET_MACRO_ERR_INVALID_PARAMETERS;
        case 7:
        case "SET_MACRO_ERR_BUSY":
            return SetMacroErrorCode.SET_MACRO_ERR_BUSY;
        case 8:
        case "SET_MACRO_ERR_NO_SPACE":
            return SetMacroErrorCode.SET_MACRO_ERR_NO_SPACE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SetMacroErrorCode.UNRECOGNIZED;
    }
}
export function setMacroErrorCodeToJSON(object) {
    switch (object) {
        case SetMacroErrorCode.SET_MACRO_ERR_OK:
            return "SET_MACRO_ERR_OK";
        case SetMacroErrorCode.SET_MACRO_ERR_GENERIC:
            return "SET_MACRO_ERR_GENERIC";
        case SetMacroErrorCode.SET_MACRO_ERR_INVALID_SLOT:
            return "SET_MACRO_ERR_INVALID_SLOT";
        case SetMacroErrorCode.SET_MACRO_ERR_INVALID_NAME:
            return "SET_MACRO_ERR_INVALID_NAME";
        case SetMacroErrorCode.SET_MACRO_ERR_INVALID_STEP:
            return "SET_MACRO_ERR_INVALID_STEP";
        case SetMacroErrorCode.SET_MACRO_ERR_INVALID_BEHAVIOR:
            return "SET_MACRO_ERR_INVALID_BEHAVIOR";
        case SetMacroErrorCode.SET_MACRO_ERR_INVALID_PARAMETERS:
            return "SET_MACRO_ERR_INVALID_PARAMETERS";
        case SetMacroErrorCode.SET_MACRO_ERR_BUSY:
            return "SET_MACRO_ERR_BUSY";
        case SetMacroErrorCode.SET_MACRO_ERR_NO_SPACE:
            return "SET_MACRO_ERR_NO_SPACE";
        case SetMacroErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SaveChangesErrorCode;
(function (SaveChangesErrorCode) {
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_OK"] = 0] = "SAVE_CHANGES_ERR_OK";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_GENERIC"] = 1] = "SAVE_CHANGES_ERR_GENERIC";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NOT_SUPPORTED"] = 2] = "SAVE_CHANGES_ERR_NOT_SUPPORTED";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NO_SPACE"] = 3] = "SAVE_CHANGES_ERR_NO_SPACE";
    SaveChangesErrorCode[SaveChangesErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SaveChangesErrorCode || (SaveChangesErrorCode = {}));
export function saveChangesErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SAVE_CHANGES_ERR_OK":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_OK;
        case 1:
        case "SAVE_CHANGES_ERR_GENERIC":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC;
        case 2:
        case "SAVE_CHANGES_ERR_NOT_SUPPORTED":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED;
        case 3:
        case "SAVE_CHANGES_ERR_NO_SPACE":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SaveChangesErrorCode.UNRECOGNIZED;
    }
}
export function saveChangesErrorCodeToJSON(object) {
    switch (object) {
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_OK:
            return "SAVE_CHANGES_ERR_OK";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC:
            return "SAVE_CHANGES_ERR_GENERIC";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED:
            return "SAVE_CHANGES_ERR_NOT_SUPPORTED";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE:
            return "SAVE_CHANGES_ERR_NO_SPACE";
        case SaveChangesErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseRequest() {
    return {
        getMacroState: undefined,
        setMacro: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
        getMacro: undefined,
        setTapMs: undefined,
        resetMacro: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getMacroState !== undefined) {
            writer.uint32(8).bool(message.getMacroState);
        }
        if (message.setMacro !== undefined) {
            SetMacroRequest.encode(message.setMacro, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            writer.uint32(32).bool(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        if (message.getMacro !== undefined) {
            GetMacroRequest.encode(message.getMacro, writer.uint32(50).fork()).ldelim();
        }
        if (message.setTapMs !== undefined) {
            SetTapMsRequest.encode(message.setTapMs, writer.uint32(58).fork()).ldelim();
        }
        if (message.resetMacro !== undefined) {
            ResetMacroRequest.encode(message.resetMacro, writer.uint32(66).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.getMacroState = reader.bool();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setMacro = SetMacroRequest.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.saveChanges = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.getMacro = GetMacroRequest.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.setTapMs = SetTapMsRequest.decode(reader, reader.uint32());
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.resetMacro = ResetMacroRequest.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getMacroState: isSet(object.getMacroState) ? globalThis.Boolean(object.getMacroState) : undefined,
            setMacro: isSet(object.setMacro) ? SetMacroRequest.fromJSON(object.setMacro) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? globalThis.Boolean(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
            getMacro: isSet(object.getMacro) ? GetMacroRequest.fromJSON(object.getMacro) : undefined,
            setTapMs: isSet(object.setTapMs) ? SetTapMsRequest.fromJSON(object.setTapMs) : undefined,
            resetMacro: isSet(object.resetMacro) ? ResetMacroRequest.fromJSON(object.resetMacro) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getMacroState !== undefined) {
            obj.getMacroState = message.getMacroState;
        }
        if (message.setMacro !== undefined) {
            obj.setMacro = SetMacroRequest.toJSON(message.setMacro);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = message.saveChanges;
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        if (message.getMacro !== undefined) {
            obj.getMacro = GetMacroRequest.toJSON(message.getMacro);
        }
        if (message.setTapMs !== undefined) {
            obj.setTapMs = SetTapMsRequest.toJSON(message.setTapMs);
        }
        if (message.resetMacro !== undefined) {
            obj.resetMacro = ResetMacroRequest.toJSON(message.resetMacro);
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.getMacroState = object.getMacroState ?? undefined;
        message.setMacro = (object.setMacro !== undefined && object.setMacro !== null)
            ? SetMacroRequest.fromPartial(object.setMacro)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = object.saveChanges ?? undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        message.getMacro = (object.getMacro !== undefined && object.getMacro !== null)
            ? GetMacroRequest.fromPartial(object.getMacro)
            : undefined;
        message.setTapMs = (object.setTapMs !== undefined && object.setTapMs !== null)
            ? SetTapMsRequest.fromPartial(object.setTapMs)
            : undefined;
        message.resetMacro = (object.resetMacro !== undefined && object.resetMacro !== null)
            ? ResetMacroRequest.fromPartial(object.resetMacro)
            : undefined;
        return message;
    },
};
function createBaseResponse() {
    return {
        getMacroState: undefined,
        setMacro: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
        getMacro: undefined,
        setTapMs: undefined,
        resetMacro: undefined,
    };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getMacroState !== undefined) {
            MacroState.encode(message.getMacroState, writer.uint32(10).fork()).ldelim();
        }
        if (message.setMacro !== undefined) {
            SetMacroResponse.encode(message.setMacro, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            SaveChangesResponse.encode(message.saveChanges, writer.uint32(34).fork()).ldelim();
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        if (message.getMacro !== undefined) {
            GetMacroResponse.encode(message.getMacro, writer.uint32(50).fork()).ldelim();
        }
        if (message.setTapMs !== undefined) {
            SetTapMsResponse.encode(message.setTapMs, writer.uint32(58).fork()).ldelim();
        }
        if (message.resetMacro !== undefined) {
            ResetMacroResponse.encode(message.resetMacro, writer.uint32(66).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.getMacroState = MacroState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setMacro = SetMacroResponse.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.getMacro = GetMacroResponse.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.setTapMs = SetTapMsResponse.decode(reader, reader.uint32());
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.resetMacro = ResetMacroResponse.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getMacroState: isSet(object.getMacroState) ? MacroState.fromJSON(object.getMacroState) : undefined,
            setMacro: isSet(object.setMacro) ? SetMacroResponse.fromJSON(object.setMacro) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
            getMacro: isSet(object.getMacro) ? GetMacroResponse.fromJSON(object.getMacro) : undefined,
            setTapMs: isSet(object.setTapMs) ? SetTapMsResponse.fromJSON(object.setTapMs) : undefined,
            resetMacro: isSet(object.resetMacro) ? ResetMacroResponse.fromJSON(object.resetMacro) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getMacroState !== undefined) {
            obj.getMacroState = MacroState.toJSON(message.getMacroState);
        }
        if (message.setMacro !== undefined) {
            obj.setMacro = SetMacroResponse.toJSON(message.setMacro);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        if (message.getMacro !== undefined) {
            obj.getMacro = GetMacroResponse.toJSON(message.getMacro);
        }
        if (message.setTapMs !== undefined) {
            obj.setTapMs = SetTapMsResponse.toJSON(message.setTapMs);
        }
        if (message.resetMacro !== undefined) {
            obj.resetMacro = ResetMacroResponse.toJSON(message.resetMacro);
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.getMacroState = (object.getMacroState !== undefined && object.getMacroState !== null)
            ? MacroState.fromPartial(object.getMacroState)
            : undefined;
        message.setMacro = (object.setMacro !== undefined && object.setMacro !== null)
            ? SetMacroResponse.fromPartial(object.setMacro)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
            ? SaveChangesResponse.fromPartial(object.saveChanges)
            : undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        message.getMacro = (object.getMacro !== undefined && object.getMacro !== null)
            ? GetMacroResponse.fromPartial(object.getMacro)
            : undefined;
        message.setTapMs = (object.setTapMs !== undefined && object.setTapMs !== null)
            ? SetTapMsResponse.fromPartial(object.setTapMs)
            : undefined;
        message.resetMacro = (object.resetMacro !== undefined && object.resetMacro !== null)
            ? ResetMacroResponse.fromPartial(object.resetMacro)
            : undefined;
        return message;
    },
};
function createBaseNotification() {
    return { macroStateChanged: undefined, unsavedChangesStatusChanged: undefined };
}
export const Notification = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.macroStateChanged !== undefined) {
            MacroState.encode(message.macroStateChanged, writer.uint32(10).fork()).ldelim();
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            writer.uint32(16).bool(message.unsavedChangesStatusChanged);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNotification();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.macroStateChanged = MacroState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.unsavedChangesStatusChanged = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            macroStateChanged: isSet(object.macroStateChanged) ? MacroState.fromJSON(object.macroStateChanged) : undefined,
            unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
                ? globalThis.Boolean(object.unsavedChangesStatusChanged)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.macroStateChanged !== undefined) {
            obj.macroStateChanged = MacroState.toJSON(message.macroStateChanged);
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
        }
        return obj;
    },
    create(base) {
        return Notification.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNotification();
        message.macroStateChanged = (object.macroStateChanged !== undefined && object.macroStateChanged !== null)
            ? MacroState.fromPartial(object.macroStateChanged)
            : undefined;
        message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
        return message;
    },
};
function createBaseMacroState() {
    return {
        schemaVersion: 0,
        maxMacros: 0,
        maxStepsPerMacro: 0,
        macros: [],
        dirty: false,
        tapMs: 0,
        poolBytesTotal: 0,
        poolBytesUsed: 0,
        maxMacroBytes: 0,
    };
}
export const MacroState = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.schemaVersion !== 0) {
            writer.uint32(8).uint32(message.schemaVersion);
        }
        if (message.maxMacros !== 0) {
            writer.uint32(16).uint32(message.maxMacros);
        }
        if (message.maxStepsPerMacro !== 0) {
            writer.uint32(24).uint32(message.maxStepsPerMacro);
        }
        for (const v of message.macros) {
            Macro.encode(v, writer.uint32(34).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(40).bool(message.dirty);
        }
        if (message.tapMs !== 0) {
            writer.uint32(48).uint32(message.tapMs);
        }
        if (message.poolBytesTotal !== 0) {
            writer.uint32(56).uint32(message.poolBytesTotal);
        }
        if (message.poolBytesUsed !== 0) {
            writer.uint32(64).uint32(message.poolBytesUsed);
        }
        if (message.maxMacroBytes !== 0) {
            writer.uint32(72).uint32(message.maxMacroBytes);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMacroState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.schemaVersion = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.maxMacros = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.maxStepsPerMacro = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.macros.push(Macro.decode(reader, reader.uint32()));
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.tapMs = reader.uint32();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.poolBytesTotal = reader.uint32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.poolBytesUsed = reader.uint32();
                    continue;
                case 9:
                    if (tag !== 72) {
                        break;
                    }
                    message.maxMacroBytes = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            schemaVersion: isSet(object.schemaVersion) ? globalThis.Number(object.schemaVersion) : 0,
            maxMacros: isSet(object.maxMacros) ? globalThis.Number(object.maxMacros) : 0,
            maxStepsPerMacro: isSet(object.maxStepsPerMacro) ? globalThis.Number(object.maxStepsPerMacro) : 0,
            macros: globalThis.Array.isArray(object?.macros) ? object.macros.map((e) => Macro.fromJSON(e)) : [],
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
            tapMs: isSet(object.tapMs) ? globalThis.Number(object.tapMs) : 0,
            poolBytesTotal: isSet(object.poolBytesTotal) ? globalThis.Number(object.poolBytesTotal) : 0,
            poolBytesUsed: isSet(object.poolBytesUsed) ? globalThis.Number(object.poolBytesUsed) : 0,
            maxMacroBytes: isSet(object.maxMacroBytes) ? globalThis.Number(object.maxMacroBytes) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.schemaVersion !== 0) {
            obj.schemaVersion = Math.round(message.schemaVersion);
        }
        if (message.maxMacros !== 0) {
            obj.maxMacros = Math.round(message.maxMacros);
        }
        if (message.maxStepsPerMacro !== 0) {
            obj.maxStepsPerMacro = Math.round(message.maxStepsPerMacro);
        }
        if (message.macros?.length) {
            obj.macros = message.macros.map((e) => Macro.toJSON(e));
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        if (message.tapMs !== 0) {
            obj.tapMs = Math.round(message.tapMs);
        }
        if (message.poolBytesTotal !== 0) {
            obj.poolBytesTotal = Math.round(message.poolBytesTotal);
        }
        if (message.poolBytesUsed !== 0) {
            obj.poolBytesUsed = Math.round(message.poolBytesUsed);
        }
        if (message.maxMacroBytes !== 0) {
            obj.maxMacroBytes = Math.round(message.maxMacroBytes);
        }
        return obj;
    },
    create(base) {
        return MacroState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMacroState();
        message.schemaVersion = object.schemaVersion ?? 0;
        message.maxMacros = object.maxMacros ?? 0;
        message.maxStepsPerMacro = object.maxStepsPerMacro ?? 0;
        message.macros = object.macros?.map((e) => Macro.fromPartial(e)) || [];
        message.dirty = object.dirty ?? false;
        message.tapMs = object.tapMs ?? 0;
        message.poolBytesTotal = object.poolBytesTotal ?? 0;
        message.poolBytesUsed = object.poolBytesUsed ?? 0;
        message.maxMacroBytes = object.maxMacroBytes ?? 0;
        return message;
    },
};
function createBaseMacro() {
    return {
        slotIndex: 0,
        behaviorId: 0,
        name: "",
        enabled: false,
        steps: [],
        dirty: false,
        packedKeys: new Uint8Array(0),
        encodedSize: 0,
    };
}
export const Macro = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.slotIndex !== 0) {
            writer.uint32(8).uint32(message.slotIndex);
        }
        if (message.behaviorId !== 0) {
            writer.uint32(16).sint32(message.behaviorId);
        }
        if (message.name !== "") {
            writer.uint32(26).string(message.name);
        }
        if (message.enabled !== false) {
            writer.uint32(32).bool(message.enabled);
        }
        for (const v of message.steps) {
            MacroStep.encode(v, writer.uint32(42).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(48).bool(message.dirty);
        }
        if (message.packedKeys.length !== 0) {
            writer.uint32(58).bytes(message.packedKeys);
        }
        if (message.encodedSize !== 0) {
            writer.uint32(64).uint32(message.encodedSize);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMacro();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.slotIndex = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.behaviorId = reader.sint32();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.enabled = reader.bool();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.steps.push(MacroStep.decode(reader, reader.uint32()));
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.packedKeys = reader.bytes();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.encodedSize = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            slotIndex: isSet(object.slotIndex) ? globalThis.Number(object.slotIndex) : 0,
            behaviorId: isSet(object.behaviorId) ? globalThis.Number(object.behaviorId) : 0,
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
            steps: globalThis.Array.isArray(object?.steps) ? object.steps.map((e) => MacroStep.fromJSON(e)) : [],
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
            packedKeys: isSet(object.packedKeys) ? bytesFromBase64(object.packedKeys) : new Uint8Array(0),
            encodedSize: isSet(object.encodedSize) ? globalThis.Number(object.encodedSize) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.slotIndex !== 0) {
            obj.slotIndex = Math.round(message.slotIndex);
        }
        if (message.behaviorId !== 0) {
            obj.behaviorId = Math.round(message.behaviorId);
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.enabled !== false) {
            obj.enabled = message.enabled;
        }
        if (message.steps?.length) {
            obj.steps = message.steps.map((e) => MacroStep.toJSON(e));
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        if (message.packedKeys.length !== 0) {
            obj.packedKeys = base64FromBytes(message.packedKeys);
        }
        if (message.encodedSize !== 0) {
            obj.encodedSize = Math.round(message.encodedSize);
        }
        return obj;
    },
    create(base) {
        return Macro.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMacro();
        message.slotIndex = object.slotIndex ?? 0;
        message.behaviorId = object.behaviorId ?? 0;
        message.name = object.name ?? "";
        message.enabled = object.enabled ?? false;
        message.steps = object.steps?.map((e) => MacroStep.fromPartial(e)) || [];
        message.dirty = object.dirty ?? false;
        message.packedKeys = object.packedKeys ?? new Uint8Array(0);
        message.encodedSize = object.encodedSize ?? 0;
        return message;
    },
};
function createBaseMacroStep() {
    return { action: 0, binding: undefined, waitMs: 0, packedKeysOffset: 0, packedKeysLength: 0 };
}
export const MacroStep = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.action !== 0) {
            writer.uint32(8).int32(message.action);
        }
        if (message.binding !== undefined) {
            BehaviorBinding.encode(message.binding, writer.uint32(18).fork()).ldelim();
        }
        if (message.waitMs !== 0) {
            writer.uint32(24).uint32(message.waitMs);
        }
        if (message.packedKeysOffset !== 0) {
            writer.uint32(32).uint32(message.packedKeysOffset);
        }
        if (message.packedKeysLength !== 0) {
            writer.uint32(40).uint32(message.packedKeysLength);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMacroStep();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.action = reader.int32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.binding = BehaviorBinding.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.waitMs = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.packedKeysOffset = reader.uint32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.packedKeysLength = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            action: isSet(object.action) ? macroStepActionFromJSON(object.action) : 0,
            binding: isSet(object.binding) ? BehaviorBinding.fromJSON(object.binding) : undefined,
            waitMs: isSet(object.waitMs) ? globalThis.Number(object.waitMs) : 0,
            packedKeysOffset: isSet(object.packedKeysOffset) ? globalThis.Number(object.packedKeysOffset) : 0,
            packedKeysLength: isSet(object.packedKeysLength) ? globalThis.Number(object.packedKeysLength) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.action !== 0) {
            obj.action = macroStepActionToJSON(message.action);
        }
        if (message.binding !== undefined) {
            obj.binding = BehaviorBinding.toJSON(message.binding);
        }
        if (message.waitMs !== 0) {
            obj.waitMs = Math.round(message.waitMs);
        }
        if (message.packedKeysOffset !== 0) {
            obj.packedKeysOffset = Math.round(message.packedKeysOffset);
        }
        if (message.packedKeysLength !== 0) {
            obj.packedKeysLength = Math.round(message.packedKeysLength);
        }
        return obj;
    },
    create(base) {
        return MacroStep.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMacroStep();
        message.action = object.action ?? 0;
        message.binding = (object.binding !== undefined && object.binding !== null)
            ? BehaviorBinding.fromPartial(object.binding)
            : undefined;
        message.waitMs = object.waitMs ?? 0;
        message.packedKeysOffset = object.packedKeysOffset ?? 0;
        message.packedKeysLength = object.packedKeysLength ?? 0;
        return message;
    },
};
function createBaseGetMacroRequest() {
    return { slotIndex: 0 };
}
export const GetMacroRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.slotIndex !== 0) {
            writer.uint32(8).uint32(message.slotIndex);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetMacroRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.slotIndex = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { slotIndex: isSet(object.slotIndex) ? globalThis.Number(object.slotIndex) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.slotIndex !== 0) {
            obj.slotIndex = Math.round(message.slotIndex);
        }
        return obj;
    },
    create(base) {
        return GetMacroRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetMacroRequest();
        message.slotIndex = object.slotIndex ?? 0;
        return message;
    },
};
function createBaseGetMacroResponse() {
    return { macro: undefined };
}
export const GetMacroResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.macro !== undefined) {
            Macro.encode(message.macro, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetMacroResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.macro = Macro.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { macro: isSet(object.macro) ? Macro.fromJSON(object.macro) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.macro !== undefined) {
            obj.macro = Macro.toJSON(message.macro);
        }
        return obj;
    },
    create(base) {
        return GetMacroResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetMacroResponse();
        message.macro = (object.macro !== undefined && object.macro !== null) ? Macro.fromPartial(object.macro) : undefined;
        return message;
    },
};
function createBaseSetMacroRequest() {
    return { macro: undefined };
}
export const SetMacroRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.macro !== undefined) {
            Macro.encode(message.macro, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetMacroRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.macro = Macro.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { macro: isSet(object.macro) ? Macro.fromJSON(object.macro) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.macro !== undefined) {
            obj.macro = Macro.toJSON(message.macro);
        }
        return obj;
    },
    create(base) {
        return SetMacroRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetMacroRequest();
        message.macro = (object.macro !== undefined && object.macro !== null) ? Macro.fromPartial(object.macro) : undefined;
        return message;
    },
};
function createBaseSetMacroResponse() {
    return { ok: undefined, err: undefined };
}
export const SetMacroResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            SetMacroOk.encode(message.ok, writer.uint32(10).fork()).ldelim();
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetMacroResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.ok = SetMacroOk.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? SetMacroOk.fromJSON(object.ok) : undefined,
            err: isSet(object.err) ? setMacroErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = SetMacroOk.toJSON(message.ok);
        }
        if (message.err !== undefined) {
            obj.err = setMacroErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SetMacroResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetMacroResponse();
        message.ok = (object.ok !== undefined && object.ok !== null) ? SetMacroOk.fromPartial(object.ok) : undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function createBaseSetMacroOk() {
    return { macro: undefined, dirty: false };
}
export const SetMacroOk = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.macro !== undefined) {
            Macro.encode(message.macro, writer.uint32(10).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(16).bool(message.dirty);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetMacroOk();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.macro = Macro.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            macro: isSet(object.macro) ? Macro.fromJSON(object.macro) : undefined,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.macro !== undefined) {
            obj.macro = Macro.toJSON(message.macro);
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        return obj;
    },
    create(base) {
        return SetMacroOk.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetMacroOk();
        message.macro = (object.macro !== undefined && object.macro !== null) ? Macro.fromPartial(object.macro) : undefined;
        message.dirty = object.dirty ?? false;
        return message;
    },
};
function createBaseSetTapMsRequest() {
    return { tapMs: 0 };
}
export const SetTapMsRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.tapMs !== 0) {
            writer.uint32(8).uint32(message.tapMs);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetTapMsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.tapMs = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { tapMs: isSet(object.tapMs) ? globalThis.Number(object.tapMs) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.tapMs !== 0) {
            obj.tapMs = Math.round(message.tapMs);
        }
        return obj;
    },
    create(base) {
        return SetTapMsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetTapMsRequest();
        message.tapMs = object.tapMs ?? 0;
        return message;
    },
};
function createBaseSetTapMsResponse() {
    return { tapMs: 0, dirty: false };
}
export const SetTapMsResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.tapMs !== 0) {
            writer.uint32(8).uint32(message.tapMs);
        }
        if (message.dirty !== false) {
            writer.uint32(16).bool(message.dirty);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetTapMsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.tapMs = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            tapMs: isSet(object.tapMs) ? globalThis.Number(object.tapMs) : 0,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.tapMs !== 0) {
            obj.tapMs = Math.round(message.tapMs);
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        return obj;
    },
    create(base) {
        return SetTapMsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetTapMsResponse();
        message.tapMs = object.tapMs ?? 0;
        message.dirty = object.dirty ?? false;
        return message;
    },
};
function createBaseResetMacroRequest() {
    return { slotIndex: 0 };
}
export const ResetMacroRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.slotIndex !== 0) {
            writer.uint32(8).uint32(message.slotIndex);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResetMacroRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.slotIndex = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { slotIndex: isSet(object.slotIndex) ? globalThis.Number(object.slotIndex) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.slotIndex !== 0) {
            obj.slotIndex = Math.round(message.slotIndex);
        }
        return obj;
    },
    create(base) {
        return ResetMacroRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResetMacroRequest();
        message.slotIndex = object.slotIndex ?? 0;
        return message;
    },
};
function createBaseResetMacroResponse() {
    return { ok: undefined, err: undefined };
}
export const ResetMacroResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            SetMacroOk.encode(message.ok, writer.uint32(10).fork()).ldelim();
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResetMacroResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.ok = SetMacroOk.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? SetMacroOk.fromJSON(object.ok) : undefined,
            err: isSet(object.err) ? setMacroErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = SetMacroOk.toJSON(message.ok);
        }
        if (message.err !== undefined) {
            obj.err = setMacroErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return ResetMacroResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResetMacroResponse();
        message.ok = (object.ok !== undefined && object.ok !== null) ? SetMacroOk.fromPartial(object.ok) : undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function createBaseSaveChangesResponse() {
    return { ok: undefined, err: undefined };
}
export const SaveChangesResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            writer.uint32(8).bool(message.ok);
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveChangesResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.ok = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
            err: isSet(object.err) ? saveChangesErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = message.ok;
        }
        if (message.err !== undefined) {
            obj.err = saveChangesErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SaveChangesResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveChangesResponse();
        message.ok = object.ok ?? undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function bytesFromBase64(b64) {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
        arr[i] = bin.charCodeAt(i);
    }
    return arr;
}
function base64FromBytes(arr) {
    const bin = [];
    arr.forEach((byte) => {
        bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
}
function isSet(value) {
    return value !== null && value !== undefined;
}
