// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: meteorite.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
export const protobufPackage = "zmk.meteorite";
export var SetConfigResponse;
(function (SetConfigResponse) {
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_OK"] = 0] = "SET_CONFIG_RESP_OK";
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_ERR_INVALID_VALUE"] = 1] = "SET_CONFIG_RESP_ERR_INVALID_VALUE";
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_ERR_GENERIC"] = 2] = "SET_CONFIG_RESP_ERR_GENERIC";
    SetConfigResponse[SetConfigResponse["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SetConfigResponse || (SetConfigResponse = {}));
export function setConfigResponseFromJSON(object) {
    switch (object) {
        case 0:
        case "SET_CONFIG_RESP_OK":
            return SetConfigResponse.SET_CONFIG_RESP_OK;
        case 1:
        case "SET_CONFIG_RESP_ERR_INVALID_VALUE":
            return SetConfigResponse.SET_CONFIG_RESP_ERR_INVALID_VALUE;
        case 2:
        case "SET_CONFIG_RESP_ERR_GENERIC":
            return SetConfigResponse.SET_CONFIG_RESP_ERR_GENERIC;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SetConfigResponse.UNRECOGNIZED;
    }
}
export function setConfigResponseToJSON(object) {
    switch (object) {
        case SetConfigResponse.SET_CONFIG_RESP_OK:
            return "SET_CONFIG_RESP_OK";
        case SetConfigResponse.SET_CONFIG_RESP_ERR_INVALID_VALUE:
            return "SET_CONFIG_RESP_ERR_INVALID_VALUE";
        case SetConfigResponse.SET_CONFIG_RESP_ERR_GENERIC:
            return "SET_CONFIG_RESP_ERR_GENERIC";
        case SetConfigResponse.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SaveChangesErrorCode;
(function (SaveChangesErrorCode) {
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_OK"] = 0] = "SAVE_CHANGES_ERR_OK";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_GENERIC"] = 1] = "SAVE_CHANGES_ERR_GENERIC";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NOT_SUPPORTED"] = 2] = "SAVE_CHANGES_ERR_NOT_SUPPORTED";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NO_SPACE"] = 3] = "SAVE_CHANGES_ERR_NO_SPACE";
    SaveChangesErrorCode[SaveChangesErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SaveChangesErrorCode || (SaveChangesErrorCode = {}));
export function saveChangesErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SAVE_CHANGES_ERR_OK":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_OK;
        case 1:
        case "SAVE_CHANGES_ERR_GENERIC":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC;
        case 2:
        case "SAVE_CHANGES_ERR_NOT_SUPPORTED":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED;
        case 3:
        case "SAVE_CHANGES_ERR_NO_SPACE":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SaveChangesErrorCode.UNRECOGNIZED;
    }
}
export function saveChangesErrorCodeToJSON(object) {
    switch (object) {
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_OK:
            return "SAVE_CHANGES_ERR_OK";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC:
            return "SAVE_CHANGES_ERR_GENERIC";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED:
            return "SAVE_CHANGES_ERR_NOT_SUPPORTED";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE:
            return "SAVE_CHANGES_ERR_NO_SPACE";
        case SaveChangesErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var ConfigFieldKind;
(function (ConfigFieldKind) {
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_RANGE"] = 0] = "CONFIG_FIELD_KIND_RANGE";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_TOGGLE"] = 1] = "CONFIG_FIELD_KIND_TOGGLE";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_ENUM"] = 2] = "CONFIG_FIELD_KIND_ENUM";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_INDEXED"] = 3] = "CONFIG_FIELD_KIND_INDEXED";
    ConfigFieldKind[ConfigFieldKind["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ConfigFieldKind || (ConfigFieldKind = {}));
export function configFieldKindFromJSON(object) {
    switch (object) {
        case 0:
        case "CONFIG_FIELD_KIND_RANGE":
            return ConfigFieldKind.CONFIG_FIELD_KIND_RANGE;
        case 1:
        case "CONFIG_FIELD_KIND_TOGGLE":
            return ConfigFieldKind.CONFIG_FIELD_KIND_TOGGLE;
        case 2:
        case "CONFIG_FIELD_KIND_ENUM":
            return ConfigFieldKind.CONFIG_FIELD_KIND_ENUM;
        case 3:
        case "CONFIG_FIELD_KIND_INDEXED":
            return ConfigFieldKind.CONFIG_FIELD_KIND_INDEXED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ConfigFieldKind.UNRECOGNIZED;
    }
}
export function configFieldKindToJSON(object) {
    switch (object) {
        case ConfigFieldKind.CONFIG_FIELD_KIND_RANGE:
            return "CONFIG_FIELD_KIND_RANGE";
        case ConfigFieldKind.CONFIG_FIELD_KIND_TOGGLE:
            return "CONFIG_FIELD_KIND_TOGGLE";
        case ConfigFieldKind.CONFIG_FIELD_KIND_ENUM:
            return "CONFIG_FIELD_KIND_ENUM";
        case ConfigFieldKind.CONFIG_FIELD_KIND_INDEXED:
            return "CONFIG_FIELD_KIND_INDEXED";
        case ConfigFieldKind.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var EncoderSide;
(function (EncoderSide) {
    EncoderSide[EncoderSide["ENCODER_SIDE_LEFT"] = 0] = "ENCODER_SIDE_LEFT";
    EncoderSide[EncoderSide["ENCODER_SIDE_RIGHT"] = 1] = "ENCODER_SIDE_RIGHT";
    EncoderSide[EncoderSide["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(EncoderSide || (EncoderSide = {}));
export function encoderSideFromJSON(object) {
    switch (object) {
        case 0:
        case "ENCODER_SIDE_LEFT":
            return EncoderSide.ENCODER_SIDE_LEFT;
        case 1:
        case "ENCODER_SIDE_RIGHT":
            return EncoderSide.ENCODER_SIDE_RIGHT;
        case -1:
        case "UNRECOGNIZED":
        default:
            return EncoderSide.UNRECOGNIZED;
    }
}
export function encoderSideToJSON(object) {
    switch (object) {
        case EncoderSide.ENCODER_SIDE_LEFT:
            return "ENCODER_SIDE_LEFT";
        case EncoderSide.ENCODER_SIDE_RIGHT:
            return "ENCODER_SIDE_RIGHT";
        case EncoderSide.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var EncoderDirection;
(function (EncoderDirection) {
    EncoderDirection[EncoderDirection["ENCODER_DIRECTION_CW"] = 0] = "ENCODER_DIRECTION_CW";
    EncoderDirection[EncoderDirection["ENCODER_DIRECTION_CCW"] = 1] = "ENCODER_DIRECTION_CCW";
    EncoderDirection[EncoderDirection["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(EncoderDirection || (EncoderDirection = {}));
export function encoderDirectionFromJSON(object) {
    switch (object) {
        case 0:
        case "ENCODER_DIRECTION_CW":
            return EncoderDirection.ENCODER_DIRECTION_CW;
        case 1:
        case "ENCODER_DIRECTION_CCW":
            return EncoderDirection.ENCODER_DIRECTION_CCW;
        case -1:
        case "UNRECOGNIZED":
        default:
            return EncoderDirection.UNRECOGNIZED;
    }
}
export function encoderDirectionToJSON(object) {
    switch (object) {
        case EncoderDirection.ENCODER_DIRECTION_CW:
            return "ENCODER_DIRECTION_CW";
        case EncoderDirection.ENCODER_DIRECTION_CCW:
            return "ENCODER_DIRECTION_CCW";
        case EncoderDirection.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseRequest() {
    return {
        getConfigState: undefined,
        setConfig: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getConfigState !== undefined) {
            writer.uint32(8).bool(message.getConfigState);
        }
        if (message.setConfig !== undefined) {
            SetConfigRequest.encode(message.setConfig, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            writer.uint32(32).bool(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.getConfigState = reader.bool();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setConfig = SetConfigRequest.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.saveChanges = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getConfigState: isSet(object.getConfigState) ? globalThis.Boolean(object.getConfigState) : undefined,
            setConfig: isSet(object.setConfig) ? SetConfigRequest.fromJSON(object.setConfig) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? globalThis.Boolean(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getConfigState !== undefined) {
            obj.getConfigState = message.getConfigState;
        }
        if (message.setConfig !== undefined) {
            obj.setConfig = SetConfigRequest.toJSON(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = message.saveChanges;
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.getConfigState = object.getConfigState ?? undefined;
        message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
            ? SetConfigRequest.fromPartial(object.setConfig)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = object.saveChanges ?? undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseResponse() {
    return {
        getConfigState: undefined,
        setConfig: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getConfigState !== undefined) {
            ConfigState.encode(message.getConfigState, writer.uint32(10).fork()).ldelim();
        }
        if (message.setConfig !== undefined) {
            writer.uint32(16).int32(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            SaveChangesResponse.encode(message.saveChanges, writer.uint32(34).fork()).ldelim();
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.getConfigState = ConfigState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.setConfig = reader.int32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getConfigState: isSet(object.getConfigState) ? ConfigState.fromJSON(object.getConfigState) : undefined,
            setConfig: isSet(object.setConfig) ? setConfigResponseFromJSON(object.setConfig) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getConfigState !== undefined) {
            obj.getConfigState = ConfigState.toJSON(message.getConfigState);
        }
        if (message.setConfig !== undefined) {
            obj.setConfig = setConfigResponseToJSON(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.getConfigState = (object.getConfigState !== undefined && object.getConfigState !== null)
            ? ConfigState.fromPartial(object.getConfigState)
            : undefined;
        message.setConfig = object.setConfig ?? undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
            ? SaveChangesResponse.fromPartial(object.saveChanges)
            : undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseNotification() {
    return { configStateChanged: undefined, unsavedChangesStatusChanged: undefined };
}
export const Notification = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.configStateChanged !== undefined) {
            ConfigState.encode(message.configStateChanged, writer.uint32(10).fork()).ldelim();
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            writer.uint32(16).bool(message.unsavedChangesStatusChanged);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNotification();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.configStateChanged = ConfigState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.unsavedChangesStatusChanged = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            configStateChanged: isSet(object.configStateChanged)
                ? ConfigState.fromJSON(object.configStateChanged)
                : undefined,
            unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
                ? globalThis.Boolean(object.unsavedChangesStatusChanged)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.configStateChanged !== undefined) {
            obj.configStateChanged = ConfigState.toJSON(message.configStateChanged);
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
        }
        return obj;
    },
    create(base) {
        return Notification.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNotification();
        message.configStateChanged = (object.configStateChanged !== undefined && object.configStateChanged !== null)
            ? ConfigState.fromPartial(object.configStateChanged)
            : undefined;
        message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
        return message;
    },
};
function createBaseSetConfigRequest() {
    return { config: undefined };
}
export const SetConfigRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.config !== undefined) {
            ConfigValues.encode(message.config, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetConfigRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.config = ConfigValues.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { config: isSet(object.config) ? ConfigValues.fromJSON(object.config) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.config !== undefined) {
            obj.config = ConfigValues.toJSON(message.config);
        }
        return obj;
    },
    create(base) {
        return SetConfigRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetConfigRequest();
        message.config = (object.config !== undefined && object.config !== null)
            ? ConfigValues.fromPartial(object.config)
            : undefined;
        return message;
    },
};
function createBaseSaveChangesResponse() {
    return { ok: undefined, err: undefined };
}
export const SaveChangesResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            writer.uint32(8).bool(message.ok);
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveChangesResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.ok = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
            err: isSet(object.err) ? saveChangesErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = message.ok;
        }
        if (message.err !== undefined) {
            obj.err = saveChangesErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SaveChangesResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveChangesResponse();
        message.ok = object.ok ?? undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function createBaseConfigState() {
    return {
        schemaVersion: 0,
        firmwareFeatureVersion: "",
        fields: [],
        current: undefined,
        saved: undefined,
        defaults: undefined,
        dirty: false,
        encoderSlots: [],
    };
}
export const ConfigState = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.schemaVersion !== 0) {
            writer.uint32(8).uint32(message.schemaVersion);
        }
        if (message.firmwareFeatureVersion !== "") {
            writer.uint32(18).string(message.firmwareFeatureVersion);
        }
        for (const v of message.fields) {
            ConfigField.encode(v, writer.uint32(26).fork()).ldelim();
        }
        if (message.current !== undefined) {
            ConfigValues.encode(message.current, writer.uint32(34).fork()).ldelim();
        }
        if (message.saved !== undefined) {
            ConfigValues.encode(message.saved, writer.uint32(42).fork()).ldelim();
        }
        if (message.defaults !== undefined) {
            ConfigValues.encode(message.defaults, writer.uint32(50).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(56).bool(message.dirty);
        }
        for (const v of message.encoderSlots) {
            EncoderSlot.encode(v, writer.uint32(66).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.schemaVersion = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.firmwareFeatureVersion = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.fields.push(ConfigField.decode(reader, reader.uint32()));
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.current = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.saved = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.defaults = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.encoderSlots.push(EncoderSlot.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            schemaVersion: isSet(object.schemaVersion) ? globalThis.Number(object.schemaVersion) : 0,
            firmwareFeatureVersion: isSet(object.firmwareFeatureVersion)
                ? globalThis.String(object.firmwareFeatureVersion)
                : "",
            fields: globalThis.Array.isArray(object?.fields) ? object.fields.map((e) => ConfigField.fromJSON(e)) : [],
            current: isSet(object.current) ? ConfigValues.fromJSON(object.current) : undefined,
            saved: isSet(object.saved) ? ConfigValues.fromJSON(object.saved) : undefined,
            defaults: isSet(object.defaults) ? ConfigValues.fromJSON(object.defaults) : undefined,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
            encoderSlots: globalThis.Array.isArray(object?.encoderSlots)
                ? object.encoderSlots.map((e) => EncoderSlot.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.schemaVersion !== 0) {
            obj.schemaVersion = Math.round(message.schemaVersion);
        }
        if (message.firmwareFeatureVersion !== "") {
            obj.firmwareFeatureVersion = message.firmwareFeatureVersion;
        }
        if (message.fields?.length) {
            obj.fields = message.fields.map((e) => ConfigField.toJSON(e));
        }
        if (message.current !== undefined) {
            obj.current = ConfigValues.toJSON(message.current);
        }
        if (message.saved !== undefined) {
            obj.saved = ConfigValues.toJSON(message.saved);
        }
        if (message.defaults !== undefined) {
            obj.defaults = ConfigValues.toJSON(message.defaults);
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        if (message.encoderSlots?.length) {
            obj.encoderSlots = message.encoderSlots.map((e) => EncoderSlot.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ConfigState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigState();
        message.schemaVersion = object.schemaVersion ?? 0;
        message.firmwareFeatureVersion = object.firmwareFeatureVersion ?? "";
        message.fields = object.fields?.map((e) => ConfigField.fromPartial(e)) || [];
        message.current = (object.current !== undefined && object.current !== null)
            ? ConfigValues.fromPartial(object.current)
            : undefined;
        message.saved = (object.saved !== undefined && object.saved !== null)
            ? ConfigValues.fromPartial(object.saved)
            : undefined;
        message.defaults = (object.defaults !== undefined && object.defaults !== null)
            ? ConfigValues.fromPartial(object.defaults)
            : undefined;
        message.dirty = object.dirty ?? false;
        message.encoderSlots = object.encoderSlots?.map((e) => EncoderSlot.fromPartial(e)) || [];
        return message;
    },
};
function createBaseConfigValues() {
    return {
        cpiIdx: 0,
        scrollDiv: 0,
        rotationIdx: 0,
        scrollHRev: 0,
        scrollVRev: 0,
        scalingMode: 0,
        scrollScalingMode: 0,
        scrollLayer1: 0,
        scrollLayer2: 0,
        osMode: 0,
    };
}
export const ConfigValues = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.cpiIdx !== 0) {
            writer.uint32(8).uint32(message.cpiIdx);
        }
        if (message.scrollDiv !== 0) {
            writer.uint32(16).uint32(message.scrollDiv);
        }
        if (message.rotationIdx !== 0) {
            writer.uint32(24).uint32(message.rotationIdx);
        }
        if (message.scrollHRev !== 0) {
            writer.uint32(32).uint32(message.scrollHRev);
        }
        if (message.scrollVRev !== 0) {
            writer.uint32(40).uint32(message.scrollVRev);
        }
        if (message.scalingMode !== 0) {
            writer.uint32(48).uint32(message.scalingMode);
        }
        if (message.scrollScalingMode !== 0) {
            writer.uint32(56).uint32(message.scrollScalingMode);
        }
        if (message.scrollLayer1 !== 0) {
            writer.uint32(64).uint32(message.scrollLayer1);
        }
        if (message.scrollLayer2 !== 0) {
            writer.uint32(72).uint32(message.scrollLayer2);
        }
        if (message.osMode !== 0) {
            writer.uint32(80).uint32(message.osMode);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigValues();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.cpiIdx = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.scrollDiv = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.rotationIdx = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.scrollHRev = reader.uint32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.scrollVRev = reader.uint32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.scalingMode = reader.uint32();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.scrollScalingMode = reader.uint32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.scrollLayer1 = reader.uint32();
                    continue;
                case 9:
                    if (tag !== 72) {
                        break;
                    }
                    message.scrollLayer2 = reader.uint32();
                    continue;
                case 10:
                    if (tag !== 80) {
                        break;
                    }
                    message.osMode = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            cpiIdx: isSet(object.cpiIdx) ? globalThis.Number(object.cpiIdx) : 0,
            scrollDiv: isSet(object.scrollDiv) ? globalThis.Number(object.scrollDiv) : 0,
            rotationIdx: isSet(object.rotationIdx) ? globalThis.Number(object.rotationIdx) : 0,
            scrollHRev: isSet(object.scrollHRev) ? globalThis.Number(object.scrollHRev) : 0,
            scrollVRev: isSet(object.scrollVRev) ? globalThis.Number(object.scrollVRev) : 0,
            scalingMode: isSet(object.scalingMode) ? globalThis.Number(object.scalingMode) : 0,
            scrollScalingMode: isSet(object.scrollScalingMode) ? globalThis.Number(object.scrollScalingMode) : 0,
            scrollLayer1: isSet(object.scrollLayer1) ? globalThis.Number(object.scrollLayer1) : 0,
            scrollLayer2: isSet(object.scrollLayer2) ? globalThis.Number(object.scrollLayer2) : 0,
            osMode: isSet(object.osMode) ? globalThis.Number(object.osMode) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.cpiIdx !== 0) {
            obj.cpiIdx = Math.round(message.cpiIdx);
        }
        if (message.scrollDiv !== 0) {
            obj.scrollDiv = Math.round(message.scrollDiv);
        }
        if (message.rotationIdx !== 0) {
            obj.rotationIdx = Math.round(message.rotationIdx);
        }
        if (message.scrollHRev !== 0) {
            obj.scrollHRev = Math.round(message.scrollHRev);
        }
        if (message.scrollVRev !== 0) {
            obj.scrollVRev = Math.round(message.scrollVRev);
        }
        if (message.scalingMode !== 0) {
            obj.scalingMode = Math.round(message.scalingMode);
        }
        if (message.scrollScalingMode !== 0) {
            obj.scrollScalingMode = Math.round(message.scrollScalingMode);
        }
        if (message.scrollLayer1 !== 0) {
            obj.scrollLayer1 = Math.round(message.scrollLayer1);
        }
        if (message.scrollLayer2 !== 0) {
            obj.scrollLayer2 = Math.round(message.scrollLayer2);
        }
        if (message.osMode !== 0) {
            obj.osMode = Math.round(message.osMode);
        }
        return obj;
    },
    create(base) {
        return ConfigValues.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigValues();
        message.cpiIdx = object.cpiIdx ?? 0;
        message.scrollDiv = object.scrollDiv ?? 0;
        message.rotationIdx = object.rotationIdx ?? 0;
        message.scrollHRev = object.scrollHRev ?? 0;
        message.scrollVRev = object.scrollVRev ?? 0;
        message.scalingMode = object.scalingMode ?? 0;
        message.scrollScalingMode = object.scrollScalingMode ?? 0;
        message.scrollLayer1 = object.scrollLayer1 ?? 0;
        message.scrollLayer2 = object.scrollLayer2 ?? 0;
        message.osMode = object.osMode ?? 0;
        return message;
    },
};
function createBaseConfigField() {
    return {
        id: "",
        label: "",
        kind: 0,
        unit: "",
        min: 0,
        max: 0,
        step: 0,
        readOnly: false,
        fixedReason: "",
        options: [],
    };
}
export const ConfigField = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (message.label !== "") {
            writer.uint32(18).string(message.label);
        }
        if (message.kind !== 0) {
            writer.uint32(24).int32(message.kind);
        }
        if (message.unit !== "") {
            writer.uint32(34).string(message.unit);
        }
        if (message.min !== 0) {
            writer.uint32(40).sint32(message.min);
        }
        if (message.max !== 0) {
            writer.uint32(48).sint32(message.max);
        }
        if (message.step !== 0) {
            writer.uint32(56).sint32(message.step);
        }
        if (message.readOnly !== false) {
            writer.uint32(64).bool(message.readOnly);
        }
        if (message.fixedReason !== "") {
            writer.uint32(74).string(message.fixedReason);
        }
        for (const v of message.options) {
            ConfigFieldOption.encode(v, writer.uint32(82).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigField();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.kind = reader.int32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.unit = reader.string();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.min = reader.sint32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.max = reader.sint32();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.step = reader.sint32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.readOnly = reader.bool();
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.fixedReason = reader.string();
                    continue;
                case 10:
                    if (tag !== 82) {
                        break;
                    }
                    message.options.push(ConfigFieldOption.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            label: isSet(object.label) ? globalThis.String(object.label) : "",
            kind: isSet(object.kind) ? configFieldKindFromJSON(object.kind) : 0,
            unit: isSet(object.unit) ? globalThis.String(object.unit) : "",
            min: isSet(object.min) ? globalThis.Number(object.min) : 0,
            max: isSet(object.max) ? globalThis.Number(object.max) : 0,
            step: isSet(object.step) ? globalThis.Number(object.step) : 0,
            readOnly: isSet(object.readOnly) ? globalThis.Boolean(object.readOnly) : false,
            fixedReason: isSet(object.fixedReason) ? globalThis.String(object.fixedReason) : "",
            options: globalThis.Array.isArray(object?.options)
                ? object.options.map((e) => ConfigFieldOption.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.label !== "") {
            obj.label = message.label;
        }
        if (message.kind !== 0) {
            obj.kind = configFieldKindToJSON(message.kind);
        }
        if (message.unit !== "") {
            obj.unit = message.unit;
        }
        if (message.min !== 0) {
            obj.min = Math.round(message.min);
        }
        if (message.max !== 0) {
            obj.max = Math.round(message.max);
        }
        if (message.step !== 0) {
            obj.step = Math.round(message.step);
        }
        if (message.readOnly !== false) {
            obj.readOnly = message.readOnly;
        }
        if (message.fixedReason !== "") {
            obj.fixedReason = message.fixedReason;
        }
        if (message.options?.length) {
            obj.options = message.options.map((e) => ConfigFieldOption.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ConfigField.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigField();
        message.id = object.id ?? "";
        message.label = object.label ?? "";
        message.kind = object.kind ?? 0;
        message.unit = object.unit ?? "";
        message.min = object.min ?? 0;
        message.max = object.max ?? 0;
        message.step = object.step ?? 0;
        message.readOnly = object.readOnly ?? false;
        message.fixedReason = object.fixedReason ?? "";
        message.options = object.options?.map((e) => ConfigFieldOption.fromPartial(e)) || [];
        return message;
    },
};
function createBaseConfigFieldOption() {
    return { value: 0, label: "", displayValue: 0, displayLabel: "" };
}
export const ConfigFieldOption = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.value !== 0) {
            writer.uint32(8).sint32(message.value);
        }
        if (message.label !== "") {
            writer.uint32(18).string(message.label);
        }
        if (message.displayValue !== 0) {
            writer.uint32(24).sint32(message.displayValue);
        }
        if (message.displayLabel !== "") {
            writer.uint32(34).string(message.displayLabel);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigFieldOption();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.value = reader.sint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.displayValue = reader.sint32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.displayLabel = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            value: isSet(object.value) ? globalThis.Number(object.value) : 0,
            label: isSet(object.label) ? globalThis.String(object.label) : "",
            displayValue: isSet(object.displayValue) ? globalThis.Number(object.displayValue) : 0,
            displayLabel: isSet(object.displayLabel) ? globalThis.String(object.displayLabel) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== 0) {
            obj.value = Math.round(message.value);
        }
        if (message.label !== "") {
            obj.label = message.label;
        }
        if (message.displayValue !== 0) {
            obj.displayValue = Math.round(message.displayValue);
        }
        if (message.displayLabel !== "") {
            obj.displayLabel = message.displayLabel;
        }
        return obj;
    },
    create(base) {
        return ConfigFieldOption.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigFieldOption();
        message.value = object.value ?? 0;
        message.label = object.label ?? "";
        message.displayValue = object.displayValue ?? 0;
        message.displayLabel = object.displayLabel ?? "";
        return message;
    },
};
function createBaseEncoderSlot() {
    return { position: 0, side: 0, direction: 0, label: "", sensorIndex: 0, slotOffset: 0 };
}
export const EncoderSlot = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.position !== 0) {
            writer.uint32(8).uint32(message.position);
        }
        if (message.side !== 0) {
            writer.uint32(16).int32(message.side);
        }
        if (message.direction !== 0) {
            writer.uint32(24).int32(message.direction);
        }
        if (message.label !== "") {
            writer.uint32(34).string(message.label);
        }
        if (message.sensorIndex !== 0) {
            writer.uint32(40).uint32(message.sensorIndex);
        }
        if (message.slotOffset !== 0) {
            writer.uint32(48).uint32(message.slotOffset);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEncoderSlot();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.position = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.side = reader.int32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.direction = reader.int32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.sensorIndex = reader.uint32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.slotOffset = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            position: isSet(object.position) ? globalThis.Number(object.position) : 0,
            side: isSet(object.side) ? encoderSideFromJSON(object.side) : 0,
            direction: isSet(object.direction) ? encoderDirectionFromJSON(object.direction) : 0,
            label: isSet(object.label) ? globalThis.String(object.label) : "",
            sensorIndex: isSet(object.sensorIndex) ? globalThis.Number(object.sensorIndex) : 0,
            slotOffset: isSet(object.slotOffset) ? globalThis.Number(object.slotOffset) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.position !== 0) {
            obj.position = Math.round(message.position);
        }
        if (message.side !== 0) {
            obj.side = encoderSideToJSON(message.side);
        }
        if (message.direction !== 0) {
            obj.direction = encoderDirectionToJSON(message.direction);
        }
        if (message.label !== "") {
            obj.label = message.label;
        }
        if (message.sensorIndex !== 0) {
            obj.sensorIndex = Math.round(message.sensorIndex);
        }
        if (message.slotOffset !== 0) {
            obj.slotOffset = Math.round(message.slotOffset);
        }
        return obj;
    },
    create(base) {
        return EncoderSlot.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEncoderSlot();
        message.position = object.position ?? 0;
        message.side = object.side ?? 0;
        message.direction = object.direction ?? 0;
        message.label = object.label ?? "";
        message.sensorIndex = object.sensorIndex ?? 0;
        message.slotOffset = object.slotOffset ?? 0;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
