// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: meteorite.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";
export const protobufPackage = "zmk.meteorite";
export var SetConfigResponse;
(function (SetConfigResponse) {
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_OK"] = 0] = "SET_CONFIG_RESP_OK";
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_ERR_INVALID_VALUE"] = 1] = "SET_CONFIG_RESP_ERR_INVALID_VALUE";
    SetConfigResponse[SetConfigResponse["SET_CONFIG_RESP_ERR_GENERIC"] = 2] = "SET_CONFIG_RESP_ERR_GENERIC";
    SetConfigResponse[SetConfigResponse["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SetConfigResponse || (SetConfigResponse = {}));
export function setConfigResponseFromJSON(object) {
    switch (object) {
        case 0:
        case "SET_CONFIG_RESP_OK":
            return SetConfigResponse.SET_CONFIG_RESP_OK;
        case 1:
        case "SET_CONFIG_RESP_ERR_INVALID_VALUE":
            return SetConfigResponse.SET_CONFIG_RESP_ERR_INVALID_VALUE;
        case 2:
        case "SET_CONFIG_RESP_ERR_GENERIC":
            return SetConfigResponse.SET_CONFIG_RESP_ERR_GENERIC;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SetConfigResponse.UNRECOGNIZED;
    }
}
export function setConfigResponseToJSON(object) {
    switch (object) {
        case SetConfigResponse.SET_CONFIG_RESP_OK:
            return "SET_CONFIG_RESP_OK";
        case SetConfigResponse.SET_CONFIG_RESP_ERR_INVALID_VALUE:
            return "SET_CONFIG_RESP_ERR_INVALID_VALUE";
        case SetConfigResponse.SET_CONFIG_RESP_ERR_GENERIC:
            return "SET_CONFIG_RESP_ERR_GENERIC";
        case SetConfigResponse.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var SaveChangesErrorCode;
(function (SaveChangesErrorCode) {
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_OK"] = 0] = "SAVE_CHANGES_ERR_OK";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_GENERIC"] = 1] = "SAVE_CHANGES_ERR_GENERIC";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NOT_SUPPORTED"] = 2] = "SAVE_CHANGES_ERR_NOT_SUPPORTED";
    SaveChangesErrorCode[SaveChangesErrorCode["SAVE_CHANGES_ERR_NO_SPACE"] = 3] = "SAVE_CHANGES_ERR_NO_SPACE";
    SaveChangesErrorCode[SaveChangesErrorCode["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SaveChangesErrorCode || (SaveChangesErrorCode = {}));
export function saveChangesErrorCodeFromJSON(object) {
    switch (object) {
        case 0:
        case "SAVE_CHANGES_ERR_OK":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_OK;
        case 1:
        case "SAVE_CHANGES_ERR_GENERIC":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC;
        case 2:
        case "SAVE_CHANGES_ERR_NOT_SUPPORTED":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED;
        case 3:
        case "SAVE_CHANGES_ERR_NO_SPACE":
            return SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SaveChangesErrorCode.UNRECOGNIZED;
    }
}
export function saveChangesErrorCodeToJSON(object) {
    switch (object) {
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_OK:
            return "SAVE_CHANGES_ERR_OK";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC:
            return "SAVE_CHANGES_ERR_GENERIC";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED:
            return "SAVE_CHANGES_ERR_NOT_SUPPORTED";
        case SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE:
            return "SAVE_CHANGES_ERR_NO_SPACE";
        case SaveChangesErrorCode.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
/**
 * Ball Profile assigned per keymap layer.
 * APP is a reserved value (hidden in the v1 UI).
 */
export var BallProfile;
(function (BallProfile) {
    BallProfile[BallProfile["BALL_PROFILE_OFF"] = 0] = "BALL_PROFILE_OFF";
    BallProfile[BallProfile["BALL_PROFILE_SCROLL"] = 1] = "BALL_PROFILE_SCROLL";
    BallProfile[BallProfile["BALL_PROFILE_BROWSER"] = 2] = "BALL_PROFILE_BROWSER";
    BallProfile[BallProfile["BALL_PROFILE_DESKTOP"] = 3] = "BALL_PROFILE_DESKTOP";
    BallProfile[BallProfile["BALL_PROFILE_WINDOW"] = 4] = "BALL_PROFILE_WINDOW";
    BallProfile[BallProfile["BALL_PROFILE_APP"] = 5] = "BALL_PROFILE_APP";
    BallProfile[BallProfile["BALL_PROFILE_USER1"] = 6] = "BALL_PROFILE_USER1";
    BallProfile[BallProfile["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(BallProfile || (BallProfile = {}));
export function ballProfileFromJSON(object) {
    switch (object) {
        case 0:
        case "BALL_PROFILE_OFF":
            return BallProfile.BALL_PROFILE_OFF;
        case 1:
        case "BALL_PROFILE_SCROLL":
            return BallProfile.BALL_PROFILE_SCROLL;
        case 2:
        case "BALL_PROFILE_BROWSER":
            return BallProfile.BALL_PROFILE_BROWSER;
        case 3:
        case "BALL_PROFILE_DESKTOP":
            return BallProfile.BALL_PROFILE_DESKTOP;
        case 4:
        case "BALL_PROFILE_WINDOW":
            return BallProfile.BALL_PROFILE_WINDOW;
        case 5:
        case "BALL_PROFILE_APP":
            return BallProfile.BALL_PROFILE_APP;
        case 6:
        case "BALL_PROFILE_USER1":
            return BallProfile.BALL_PROFILE_USER1;
        case -1:
        case "UNRECOGNIZED":
        default:
            return BallProfile.UNRECOGNIZED;
    }
}
export function ballProfileToJSON(object) {
    switch (object) {
        case BallProfile.BALL_PROFILE_OFF:
            return "BALL_PROFILE_OFF";
        case BallProfile.BALL_PROFILE_SCROLL:
            return "BALL_PROFILE_SCROLL";
        case BallProfile.BALL_PROFILE_BROWSER:
            return "BALL_PROFILE_BROWSER";
        case BallProfile.BALL_PROFILE_DESKTOP:
            return "BALL_PROFILE_DESKTOP";
        case BallProfile.BALL_PROFILE_WINDOW:
            return "BALL_PROFILE_WINDOW";
        case BallProfile.BALL_PROFILE_APP:
            return "BALL_PROFILE_APP";
        case BallProfile.BALL_PROFILE_USER1:
            return "BALL_PROFILE_USER1";
        case BallProfile.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
/**
 * Shared accumulation threshold for all action profiles. Higher = less
 * sensitive (needs a larger flick before one action fires).
 *
 * The enum integer values are in sensitivity order (VERY_LIGHT most sensitive
 * .. VERY_HEAVY least), so a slider can map its position directly to the value.
 * Any future level must be appended at the end (>= 5) to keep saved configs
 * stable; do not renumber these.
 */
export var BallSensitivity;
(function (BallSensitivity) {
    /** BALL_SENSITIVITY_VERY_LIGHT - most sensitive (smallest flick) */
    BallSensitivity[BallSensitivity["BALL_SENSITIVITY_VERY_LIGHT"] = 0] = "BALL_SENSITIVITY_VERY_LIGHT";
    BallSensitivity[BallSensitivity["BALL_SENSITIVITY_LIGHT"] = 1] = "BALL_SENSITIVITY_LIGHT";
    BallSensitivity[BallSensitivity["BALL_SENSITIVITY_NORMAL"] = 2] = "BALL_SENSITIVITY_NORMAL";
    BallSensitivity[BallSensitivity["BALL_SENSITIVITY_HEAVY"] = 3] = "BALL_SENSITIVITY_HEAVY";
    /** BALL_SENSITIVITY_VERY_HEAVY - least sensitive (largest flick) */
    BallSensitivity[BallSensitivity["BALL_SENSITIVITY_VERY_HEAVY"] = 4] = "BALL_SENSITIVITY_VERY_HEAVY";
    BallSensitivity[BallSensitivity["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(BallSensitivity || (BallSensitivity = {}));
export function ballSensitivityFromJSON(object) {
    switch (object) {
        case 0:
        case "BALL_SENSITIVITY_VERY_LIGHT":
            return BallSensitivity.BALL_SENSITIVITY_VERY_LIGHT;
        case 1:
        case "BALL_SENSITIVITY_LIGHT":
            return BallSensitivity.BALL_SENSITIVITY_LIGHT;
        case 2:
        case "BALL_SENSITIVITY_NORMAL":
            return BallSensitivity.BALL_SENSITIVITY_NORMAL;
        case 3:
        case "BALL_SENSITIVITY_HEAVY":
            return BallSensitivity.BALL_SENSITIVITY_HEAVY;
        case 4:
        case "BALL_SENSITIVITY_VERY_HEAVY":
            return BallSensitivity.BALL_SENSITIVITY_VERY_HEAVY;
        case -1:
        case "UNRECOGNIZED":
        default:
            return BallSensitivity.UNRECOGNIZED;
    }
}
export function ballSensitivityToJSON(object) {
    switch (object) {
        case BallSensitivity.BALL_SENSITIVITY_VERY_LIGHT:
            return "BALL_SENSITIVITY_VERY_LIGHT";
        case BallSensitivity.BALL_SENSITIVITY_LIGHT:
            return "BALL_SENSITIVITY_LIGHT";
        case BallSensitivity.BALL_SENSITIVITY_NORMAL:
            return "BALL_SENSITIVITY_NORMAL";
        case BallSensitivity.BALL_SENSITIVITY_HEAVY:
            return "BALL_SENSITIVITY_HEAVY";
        case BallSensitivity.BALL_SENSITIVITY_VERY_HEAVY:
            return "BALL_SENSITIVITY_VERY_HEAVY";
        case BallSensitivity.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var BallDirection;
(function (BallDirection) {
    BallDirection[BallDirection["BALL_DIRECTION_LEFT"] = 0] = "BALL_DIRECTION_LEFT";
    BallDirection[BallDirection["BALL_DIRECTION_RIGHT"] = 1] = "BALL_DIRECTION_RIGHT";
    BallDirection[BallDirection["BALL_DIRECTION_UP"] = 2] = "BALL_DIRECTION_UP";
    BallDirection[BallDirection["BALL_DIRECTION_DOWN"] = 3] = "BALL_DIRECTION_DOWN";
    BallDirection[BallDirection["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(BallDirection || (BallDirection = {}));
export function ballDirectionFromJSON(object) {
    switch (object) {
        case 0:
        case "BALL_DIRECTION_LEFT":
            return BallDirection.BALL_DIRECTION_LEFT;
        case 1:
        case "BALL_DIRECTION_RIGHT":
            return BallDirection.BALL_DIRECTION_RIGHT;
        case 2:
        case "BALL_DIRECTION_UP":
            return BallDirection.BALL_DIRECTION_UP;
        case 3:
        case "BALL_DIRECTION_DOWN":
            return BallDirection.BALL_DIRECTION_DOWN;
        case -1:
        case "UNRECOGNIZED":
        default:
            return BallDirection.UNRECOGNIZED;
    }
}
export function ballDirectionToJSON(object) {
    switch (object) {
        case BallDirection.BALL_DIRECTION_LEFT:
            return "BALL_DIRECTION_LEFT";
        case BallDirection.BALL_DIRECTION_RIGHT:
            return "BALL_DIRECTION_RIGHT";
        case BallDirection.BALL_DIRECTION_UP:
            return "BALL_DIRECTION_UP";
        case BallDirection.BALL_DIRECTION_DOWN:
            return "BALL_DIRECTION_DOWN";
        case BallDirection.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
export var ConfigFieldKind;
(function (ConfigFieldKind) {
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_RANGE"] = 0] = "CONFIG_FIELD_KIND_RANGE";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_TOGGLE"] = 1] = "CONFIG_FIELD_KIND_TOGGLE";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_ENUM"] = 2] = "CONFIG_FIELD_KIND_ENUM";
    ConfigFieldKind[ConfigFieldKind["CONFIG_FIELD_KIND_INDEXED"] = 3] = "CONFIG_FIELD_KIND_INDEXED";
    ConfigFieldKind[ConfigFieldKind["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ConfigFieldKind || (ConfigFieldKind = {}));
export function configFieldKindFromJSON(object) {
    switch (object) {
        case 0:
        case "CONFIG_FIELD_KIND_RANGE":
            return ConfigFieldKind.CONFIG_FIELD_KIND_RANGE;
        case 1:
        case "CONFIG_FIELD_KIND_TOGGLE":
            return ConfigFieldKind.CONFIG_FIELD_KIND_TOGGLE;
        case 2:
        case "CONFIG_FIELD_KIND_ENUM":
            return ConfigFieldKind.CONFIG_FIELD_KIND_ENUM;
        case 3:
        case "CONFIG_FIELD_KIND_INDEXED":
            return ConfigFieldKind.CONFIG_FIELD_KIND_INDEXED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ConfigFieldKind.UNRECOGNIZED;
    }
}
export function configFieldKindToJSON(object) {
    switch (object) {
        case ConfigFieldKind.CONFIG_FIELD_KIND_RANGE:
            return "CONFIG_FIELD_KIND_RANGE";
        case ConfigFieldKind.CONFIG_FIELD_KIND_TOGGLE:
            return "CONFIG_FIELD_KIND_TOGGLE";
        case ConfigFieldKind.CONFIG_FIELD_KIND_ENUM:
            return "CONFIG_FIELD_KIND_ENUM";
        case ConfigFieldKind.CONFIG_FIELD_KIND_INDEXED:
            return "CONFIG_FIELD_KIND_INDEXED";
        case ConfigFieldKind.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseRequest() {
    return {
        getConfigState: undefined,
        setConfig: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getConfigState !== undefined) {
            writer.uint32(8).bool(message.getConfigState);
        }
        if (message.setConfig !== undefined) {
            SetConfigRequest.encode(message.setConfig, writer.uint32(18).fork()).ldelim();
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            writer.uint32(32).bool(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.getConfigState = reader.bool();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.setConfig = SetConfigRequest.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.saveChanges = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getConfigState: isSet(object.getConfigState) ? globalThis.Boolean(object.getConfigState) : undefined,
            setConfig: isSet(object.setConfig) ? SetConfigRequest.fromJSON(object.setConfig) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? globalThis.Boolean(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getConfigState !== undefined) {
            obj.getConfigState = message.getConfigState;
        }
        if (message.setConfig !== undefined) {
            obj.setConfig = SetConfigRequest.toJSON(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = message.saveChanges;
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.getConfigState = object.getConfigState ?? undefined;
        message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
            ? SetConfigRequest.fromPartial(object.setConfig)
            : undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = object.saveChanges ?? undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseResponse() {
    return {
        getConfigState: undefined,
        setConfig: undefined,
        checkUnsavedChanges: undefined,
        saveChanges: undefined,
        discardChanges: undefined,
    };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.getConfigState !== undefined) {
            ConfigState.encode(message.getConfigState, writer.uint32(10).fork()).ldelim();
        }
        if (message.setConfig !== undefined) {
            writer.uint32(16).int32(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            writer.uint32(24).bool(message.checkUnsavedChanges);
        }
        if (message.saveChanges !== undefined) {
            SaveChangesResponse.encode(message.saveChanges, writer.uint32(34).fork()).ldelim();
        }
        if (message.discardChanges !== undefined) {
            writer.uint32(40).bool(message.discardChanges);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.getConfigState = ConfigState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.setConfig = reader.int32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.checkUnsavedChanges = reader.bool();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.discardChanges = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            getConfigState: isSet(object.getConfigState) ? ConfigState.fromJSON(object.getConfigState) : undefined,
            setConfig: isSet(object.setConfig) ? setConfigResponseFromJSON(object.setConfig) : undefined,
            checkUnsavedChanges: isSet(object.checkUnsavedChanges)
                ? globalThis.Boolean(object.checkUnsavedChanges)
                : undefined,
            saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
            discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.getConfigState !== undefined) {
            obj.getConfigState = ConfigState.toJSON(message.getConfigState);
        }
        if (message.setConfig !== undefined) {
            obj.setConfig = setConfigResponseToJSON(message.setConfig);
        }
        if (message.checkUnsavedChanges !== undefined) {
            obj.checkUnsavedChanges = message.checkUnsavedChanges;
        }
        if (message.saveChanges !== undefined) {
            obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
        }
        if (message.discardChanges !== undefined) {
            obj.discardChanges = message.discardChanges;
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.getConfigState = (object.getConfigState !== undefined && object.getConfigState !== null)
            ? ConfigState.fromPartial(object.getConfigState)
            : undefined;
        message.setConfig = object.setConfig ?? undefined;
        message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
        message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
            ? SaveChangesResponse.fromPartial(object.saveChanges)
            : undefined;
        message.discardChanges = object.discardChanges ?? undefined;
        return message;
    },
};
function createBaseNotification() {
    return { configStateChanged: undefined, unsavedChangesStatusChanged: undefined };
}
export const Notification = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.configStateChanged !== undefined) {
            ConfigState.encode(message.configStateChanged, writer.uint32(10).fork()).ldelim();
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            writer.uint32(16).bool(message.unsavedChangesStatusChanged);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNotification();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.configStateChanged = ConfigState.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.unsavedChangesStatusChanged = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            configStateChanged: isSet(object.configStateChanged)
                ? ConfigState.fromJSON(object.configStateChanged)
                : undefined,
            unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
                ? globalThis.Boolean(object.unsavedChangesStatusChanged)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.configStateChanged !== undefined) {
            obj.configStateChanged = ConfigState.toJSON(message.configStateChanged);
        }
        if (message.unsavedChangesStatusChanged !== undefined) {
            obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
        }
        return obj;
    },
    create(base) {
        return Notification.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNotification();
        message.configStateChanged = (object.configStateChanged !== undefined && object.configStateChanged !== null)
            ? ConfigState.fromPartial(object.configStateChanged)
            : undefined;
        message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
        return message;
    },
};
function createBaseSetConfigRequest() {
    return { config: undefined };
}
export const SetConfigRequest = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.config !== undefined) {
            ConfigValues.encode(message.config, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetConfigRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.config = ConfigValues.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { config: isSet(object.config) ? ConfigValues.fromJSON(object.config) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.config !== undefined) {
            obj.config = ConfigValues.toJSON(message.config);
        }
        return obj;
    },
    create(base) {
        return SetConfigRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSetConfigRequest();
        message.config = (object.config !== undefined && object.config !== null)
            ? ConfigValues.fromPartial(object.config)
            : undefined;
        return message;
    },
};
function createBaseSaveChangesResponse() {
    return { ok: undefined, err: undefined };
}
export const SaveChangesResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.ok !== undefined) {
            writer.uint32(8).bool(message.ok);
        }
        if (message.err !== undefined) {
            writer.uint32(16).int32(message.err);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveChangesResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.ok = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.err = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
            err: isSet(object.err) ? saveChangesErrorCodeFromJSON(object.err) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.ok !== undefined) {
            obj.ok = message.ok;
        }
        if (message.err !== undefined) {
            obj.err = saveChangesErrorCodeToJSON(message.err);
        }
        return obj;
    },
    create(base) {
        return SaveChangesResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveChangesResponse();
        message.ok = object.ok ?? undefined;
        message.err = object.err ?? undefined;
        return message;
    },
};
function createBaseConfigState() {
    return {
        schemaVersion: 0,
        firmwareFeatureVersion: "",
        fields: [],
        current: undefined,
        saved: undefined,
        defaults: undefined,
        dirty: false,
        firmwareBuildVersion: "",
    };
}
export const ConfigState = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.schemaVersion !== 0) {
            writer.uint32(8).uint32(message.schemaVersion);
        }
        if (message.firmwareFeatureVersion !== "") {
            writer.uint32(18).string(message.firmwareFeatureVersion);
        }
        for (const v of message.fields) {
            ConfigField.encode(v, writer.uint32(26).fork()).ldelim();
        }
        if (message.current !== undefined) {
            ConfigValues.encode(message.current, writer.uint32(34).fork()).ldelim();
        }
        if (message.saved !== undefined) {
            ConfigValues.encode(message.saved, writer.uint32(42).fork()).ldelim();
        }
        if (message.defaults !== undefined) {
            ConfigValues.encode(message.defaults, writer.uint32(50).fork()).ldelim();
        }
        if (message.dirty !== false) {
            writer.uint32(56).bool(message.dirty);
        }
        if (message.firmwareBuildVersion !== "") {
            writer.uint32(74).string(message.firmwareBuildVersion);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.schemaVersion = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.firmwareFeatureVersion = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.fields.push(ConfigField.decode(reader, reader.uint32()));
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.current = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.saved = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.defaults = ConfigValues.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.dirty = reader.bool();
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.firmwareBuildVersion = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            schemaVersion: isSet(object.schemaVersion) ? globalThis.Number(object.schemaVersion) : 0,
            firmwareFeatureVersion: isSet(object.firmwareFeatureVersion)
                ? globalThis.String(object.firmwareFeatureVersion)
                : "",
            fields: globalThis.Array.isArray(object?.fields) ? object.fields.map((e) => ConfigField.fromJSON(e)) : [],
            current: isSet(object.current) ? ConfigValues.fromJSON(object.current) : undefined,
            saved: isSet(object.saved) ? ConfigValues.fromJSON(object.saved) : undefined,
            defaults: isSet(object.defaults) ? ConfigValues.fromJSON(object.defaults) : undefined,
            dirty: isSet(object.dirty) ? globalThis.Boolean(object.dirty) : false,
            firmwareBuildVersion: isSet(object.firmwareBuildVersion) ? globalThis.String(object.firmwareBuildVersion) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.schemaVersion !== 0) {
            obj.schemaVersion = Math.round(message.schemaVersion);
        }
        if (message.firmwareFeatureVersion !== "") {
            obj.firmwareFeatureVersion = message.firmwareFeatureVersion;
        }
        if (message.fields?.length) {
            obj.fields = message.fields.map((e) => ConfigField.toJSON(e));
        }
        if (message.current !== undefined) {
            obj.current = ConfigValues.toJSON(message.current);
        }
        if (message.saved !== undefined) {
            obj.saved = ConfigValues.toJSON(message.saved);
        }
        if (message.defaults !== undefined) {
            obj.defaults = ConfigValues.toJSON(message.defaults);
        }
        if (message.dirty !== false) {
            obj.dirty = message.dirty;
        }
        if (message.firmwareBuildVersion !== "") {
            obj.firmwareBuildVersion = message.firmwareBuildVersion;
        }
        return obj;
    },
    create(base) {
        return ConfigState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigState();
        message.schemaVersion = object.schemaVersion ?? 0;
        message.firmwareFeatureVersion = object.firmwareFeatureVersion ?? "";
        message.fields = object.fields?.map((e) => ConfigField.fromPartial(e)) || [];
        message.current = (object.current !== undefined && object.current !== null)
            ? ConfigValues.fromPartial(object.current)
            : undefined;
        message.saved = (object.saved !== undefined && object.saved !== null)
            ? ConfigValues.fromPartial(object.saved)
            : undefined;
        message.defaults = (object.defaults !== undefined && object.defaults !== null)
            ? ConfigValues.fromPartial(object.defaults)
            : undefined;
        message.dirty = object.dirty ?? false;
        message.firmwareBuildVersion = object.firmwareBuildVersion ?? "";
        return message;
    },
};
function createBaseConfigValues() {
    return {
        cpiIdx: 0,
        scrollDiv: 0,
        rotationIdx: 0,
        scrollHRev: 0,
        scrollVRev: 0,
        scalingMode: 0,
        scrollScalingMode: 0,
        scrollLayer1: 0,
        scrollLayer2: 0,
        osMode: 0,
        ballConfig: undefined,
        timingConfig: undefined,
    };
}
export const ConfigValues = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.cpiIdx !== 0) {
            writer.uint32(8).uint32(message.cpiIdx);
        }
        if (message.scrollDiv !== 0) {
            writer.uint32(16).uint32(message.scrollDiv);
        }
        if (message.rotationIdx !== 0) {
            writer.uint32(24).uint32(message.rotationIdx);
        }
        if (message.scrollHRev !== 0) {
            writer.uint32(32).uint32(message.scrollHRev);
        }
        if (message.scrollVRev !== 0) {
            writer.uint32(40).uint32(message.scrollVRev);
        }
        if (message.scalingMode !== 0) {
            writer.uint32(48).uint32(message.scalingMode);
        }
        if (message.scrollScalingMode !== 0) {
            writer.uint32(56).uint32(message.scrollScalingMode);
        }
        if (message.scrollLayer1 !== 0) {
            writer.uint32(64).uint32(message.scrollLayer1);
        }
        if (message.scrollLayer2 !== 0) {
            writer.uint32(72).uint32(message.scrollLayer2);
        }
        if (message.osMode !== 0) {
            writer.uint32(80).uint32(message.osMode);
        }
        if (message.ballConfig !== undefined) {
            BallConfig.encode(message.ballConfig, writer.uint32(90).fork()).ldelim();
        }
        if (message.timingConfig !== undefined) {
            TimingConfig.encode(message.timingConfig, writer.uint32(98).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigValues();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.cpiIdx = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.scrollDiv = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.rotationIdx = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.scrollHRev = reader.uint32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.scrollVRev = reader.uint32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.scalingMode = reader.uint32();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.scrollScalingMode = reader.uint32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.scrollLayer1 = reader.uint32();
                    continue;
                case 9:
                    if (tag !== 72) {
                        break;
                    }
                    message.scrollLayer2 = reader.uint32();
                    continue;
                case 10:
                    if (tag !== 80) {
                        break;
                    }
                    message.osMode = reader.uint32();
                    continue;
                case 11:
                    if (tag !== 90) {
                        break;
                    }
                    message.ballConfig = BallConfig.decode(reader, reader.uint32());
                    continue;
                case 12:
                    if (tag !== 98) {
                        break;
                    }
                    message.timingConfig = TimingConfig.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            cpiIdx: isSet(object.cpiIdx) ? globalThis.Number(object.cpiIdx) : 0,
            scrollDiv: isSet(object.scrollDiv) ? globalThis.Number(object.scrollDiv) : 0,
            rotationIdx: isSet(object.rotationIdx) ? globalThis.Number(object.rotationIdx) : 0,
            scrollHRev: isSet(object.scrollHRev) ? globalThis.Number(object.scrollHRev) : 0,
            scrollVRev: isSet(object.scrollVRev) ? globalThis.Number(object.scrollVRev) : 0,
            scalingMode: isSet(object.scalingMode) ? globalThis.Number(object.scalingMode) : 0,
            scrollScalingMode: isSet(object.scrollScalingMode) ? globalThis.Number(object.scrollScalingMode) : 0,
            scrollLayer1: isSet(object.scrollLayer1) ? globalThis.Number(object.scrollLayer1) : 0,
            scrollLayer2: isSet(object.scrollLayer2) ? globalThis.Number(object.scrollLayer2) : 0,
            osMode: isSet(object.osMode) ? globalThis.Number(object.osMode) : 0,
            ballConfig: isSet(object.ballConfig) ? BallConfig.fromJSON(object.ballConfig) : undefined,
            timingConfig: isSet(object.timingConfig) ? TimingConfig.fromJSON(object.timingConfig) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.cpiIdx !== 0) {
            obj.cpiIdx = Math.round(message.cpiIdx);
        }
        if (message.scrollDiv !== 0) {
            obj.scrollDiv = Math.round(message.scrollDiv);
        }
        if (message.rotationIdx !== 0) {
            obj.rotationIdx = Math.round(message.rotationIdx);
        }
        if (message.scrollHRev !== 0) {
            obj.scrollHRev = Math.round(message.scrollHRev);
        }
        if (message.scrollVRev !== 0) {
            obj.scrollVRev = Math.round(message.scrollVRev);
        }
        if (message.scalingMode !== 0) {
            obj.scalingMode = Math.round(message.scalingMode);
        }
        if (message.scrollScalingMode !== 0) {
            obj.scrollScalingMode = Math.round(message.scrollScalingMode);
        }
        if (message.scrollLayer1 !== 0) {
            obj.scrollLayer1 = Math.round(message.scrollLayer1);
        }
        if (message.scrollLayer2 !== 0) {
            obj.scrollLayer2 = Math.round(message.scrollLayer2);
        }
        if (message.osMode !== 0) {
            obj.osMode = Math.round(message.osMode);
        }
        if (message.ballConfig !== undefined) {
            obj.ballConfig = BallConfig.toJSON(message.ballConfig);
        }
        if (message.timingConfig !== undefined) {
            obj.timingConfig = TimingConfig.toJSON(message.timingConfig);
        }
        return obj;
    },
    create(base) {
        return ConfigValues.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigValues();
        message.cpiIdx = object.cpiIdx ?? 0;
        message.scrollDiv = object.scrollDiv ?? 0;
        message.rotationIdx = object.rotationIdx ?? 0;
        message.scrollHRev = object.scrollHRev ?? 0;
        message.scrollVRev = object.scrollVRev ?? 0;
        message.scalingMode = object.scalingMode ?? 0;
        message.scrollScalingMode = object.scrollScalingMode ?? 0;
        message.scrollLayer1 = object.scrollLayer1 ?? 0;
        message.scrollLayer2 = object.scrollLayer2 ?? 0;
        message.osMode = object.osMode ?? 0;
        message.ballConfig = (object.ballConfig !== undefined && object.ballConfig !== null)
            ? BallConfig.fromPartial(object.ballConfig)
            : undefined;
        message.timingConfig = (object.timingConfig !== undefined && object.timingConfig !== null)
            ? TimingConfig.fromPartial(object.timingConfig)
            : undefined;
        return message;
    },
};
function createBaseTimingConfig() {
    return { modTapTappingTermMs: 0, layerTapTappingTermMs: 0, idleTimeoutS: 0, idleSleepTimeoutS: 0 };
}
export const TimingConfig = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.modTapTappingTermMs !== 0) {
            writer.uint32(8).uint32(message.modTapTappingTermMs);
        }
        if (message.layerTapTappingTermMs !== 0) {
            writer.uint32(16).uint32(message.layerTapTappingTermMs);
        }
        if (message.idleTimeoutS !== 0) {
            writer.uint32(24).uint32(message.idleTimeoutS);
        }
        if (message.idleSleepTimeoutS !== 0) {
            writer.uint32(32).uint32(message.idleSleepTimeoutS);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTimingConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.modTapTappingTermMs = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.layerTapTappingTermMs = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.idleTimeoutS = reader.uint32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.idleSleepTimeoutS = reader.uint32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            modTapTappingTermMs: isSet(object.modTapTappingTermMs) ? globalThis.Number(object.modTapTappingTermMs) : 0,
            layerTapTappingTermMs: isSet(object.layerTapTappingTermMs) ? globalThis.Number(object.layerTapTappingTermMs) : 0,
            idleTimeoutS: isSet(object.idleTimeoutS) ? globalThis.Number(object.idleTimeoutS) : 0,
            idleSleepTimeoutS: isSet(object.idleSleepTimeoutS) ? globalThis.Number(object.idleSleepTimeoutS) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.modTapTappingTermMs !== 0) {
            obj.modTapTappingTermMs = Math.round(message.modTapTappingTermMs);
        }
        if (message.layerTapTappingTermMs !== 0) {
            obj.layerTapTappingTermMs = Math.round(message.layerTapTappingTermMs);
        }
        if (message.idleTimeoutS !== 0) {
            obj.idleTimeoutS = Math.round(message.idleTimeoutS);
        }
        if (message.idleSleepTimeoutS !== 0) {
            obj.idleSleepTimeoutS = Math.round(message.idleSleepTimeoutS);
        }
        return obj;
    },
    create(base) {
        return TimingConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTimingConfig();
        message.modTapTappingTermMs = object.modTapTappingTermMs ?? 0;
        message.layerTapTappingTermMs = object.layerTapTappingTermMs ?? 0;
        message.idleTimeoutS = object.idleTimeoutS ?? 0;
        message.idleSleepTimeoutS = object.idleSleepTimeoutS ?? 0;
        return message;
    },
};
function createBaseBallConfig() {
    return { layerProfiles: [], sensitivity: 0, user1Bindings: [] };
}
export const BallConfig = {
    encode(message, writer = _m0.Writer.create()) {
        writer.uint32(10).fork();
        for (const v of message.layerProfiles) {
            writer.int32(v);
        }
        writer.ldelim();
        if (message.sensitivity !== 0) {
            writer.uint32(16).int32(message.sensitivity);
        }
        for (const v of message.user1Bindings) {
            BehaviorBinding.encode(v, writer.uint32(26).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBallConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag === 8) {
                        message.layerProfiles.push(reader.int32());
                        continue;
                    }
                    if (tag === 10) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.layerProfiles.push(reader.int32());
                        }
                        continue;
                    }
                    break;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.sensitivity = reader.int32();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.user1Bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            layerProfiles: globalThis.Array.isArray(object?.layerProfiles)
                ? object.layerProfiles.map((e) => ballProfileFromJSON(e))
                : [],
            sensitivity: isSet(object.sensitivity) ? ballSensitivityFromJSON(object.sensitivity) : 0,
            user1Bindings: globalThis.Array.isArray(object?.user1Bindings)
                ? object.user1Bindings.map((e) => BehaviorBinding.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.layerProfiles?.length) {
            obj.layerProfiles = message.layerProfiles.map((e) => ballProfileToJSON(e));
        }
        if (message.sensitivity !== 0) {
            obj.sensitivity = ballSensitivityToJSON(message.sensitivity);
        }
        if (message.user1Bindings?.length) {
            obj.user1Bindings = message.user1Bindings.map((e) => BehaviorBinding.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return BallConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBallConfig();
        message.layerProfiles = object.layerProfiles?.map((e) => e) || [];
        message.sensitivity = object.sensitivity ?? 0;
        message.user1Bindings = object.user1Bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
        return message;
    },
};
function createBaseConfigField() {
    return {
        id: "",
        label: "",
        kind: 0,
        unit: "",
        min: 0,
        max: 0,
        step: 0,
        readOnly: false,
        fixedReason: "",
        options: [],
    };
}
export const ConfigField = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (message.label !== "") {
            writer.uint32(18).string(message.label);
        }
        if (message.kind !== 0) {
            writer.uint32(24).int32(message.kind);
        }
        if (message.unit !== "") {
            writer.uint32(34).string(message.unit);
        }
        if (message.min !== 0) {
            writer.uint32(40).sint32(message.min);
        }
        if (message.max !== 0) {
            writer.uint32(48).sint32(message.max);
        }
        if (message.step !== 0) {
            writer.uint32(56).sint32(message.step);
        }
        if (message.readOnly !== false) {
            writer.uint32(64).bool(message.readOnly);
        }
        if (message.fixedReason !== "") {
            writer.uint32(74).string(message.fixedReason);
        }
        for (const v of message.options) {
            ConfigFieldOption.encode(v, writer.uint32(82).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigField();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.kind = reader.int32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.unit = reader.string();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.min = reader.sint32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.max = reader.sint32();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.step = reader.sint32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.readOnly = reader.bool();
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.fixedReason = reader.string();
                    continue;
                case 10:
                    if (tag !== 82) {
                        break;
                    }
                    message.options.push(ConfigFieldOption.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            label: isSet(object.label) ? globalThis.String(object.label) : "",
            kind: isSet(object.kind) ? configFieldKindFromJSON(object.kind) : 0,
            unit: isSet(object.unit) ? globalThis.String(object.unit) : "",
            min: isSet(object.min) ? globalThis.Number(object.min) : 0,
            max: isSet(object.max) ? globalThis.Number(object.max) : 0,
            step: isSet(object.step) ? globalThis.Number(object.step) : 0,
            readOnly: isSet(object.readOnly) ? globalThis.Boolean(object.readOnly) : false,
            fixedReason: isSet(object.fixedReason) ? globalThis.String(object.fixedReason) : "",
            options: globalThis.Array.isArray(object?.options)
                ? object.options.map((e) => ConfigFieldOption.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.label !== "") {
            obj.label = message.label;
        }
        if (message.kind !== 0) {
            obj.kind = configFieldKindToJSON(message.kind);
        }
        if (message.unit !== "") {
            obj.unit = message.unit;
        }
        if (message.min !== 0) {
            obj.min = Math.round(message.min);
        }
        if (message.max !== 0) {
            obj.max = Math.round(message.max);
        }
        if (message.step !== 0) {
            obj.step = Math.round(message.step);
        }
        if (message.readOnly !== false) {
            obj.readOnly = message.readOnly;
        }
        if (message.fixedReason !== "") {
            obj.fixedReason = message.fixedReason;
        }
        if (message.options?.length) {
            obj.options = message.options.map((e) => ConfigFieldOption.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ConfigField.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigField();
        message.id = object.id ?? "";
        message.label = object.label ?? "";
        message.kind = object.kind ?? 0;
        message.unit = object.unit ?? "";
        message.min = object.min ?? 0;
        message.max = object.max ?? 0;
        message.step = object.step ?? 0;
        message.readOnly = object.readOnly ?? false;
        message.fixedReason = object.fixedReason ?? "";
        message.options = object.options?.map((e) => ConfigFieldOption.fromPartial(e)) || [];
        return message;
    },
};
function createBaseConfigFieldOption() {
    return { value: 0, label: "", displayValue: 0, displayLabel: "" };
}
export const ConfigFieldOption = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.value !== 0) {
            writer.uint32(8).sint32(message.value);
        }
        if (message.label !== "") {
            writer.uint32(18).string(message.label);
        }
        if (message.displayValue !== 0) {
            writer.uint32(24).sint32(message.displayValue);
        }
        if (message.displayLabel !== "") {
            writer.uint32(34).string(message.displayLabel);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfigFieldOption();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.value = reader.sint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.displayValue = reader.sint32();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.displayLabel = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            value: isSet(object.value) ? globalThis.Number(object.value) : 0,
            label: isSet(object.label) ? globalThis.String(object.label) : "",
            displayValue: isSet(object.displayValue) ? globalThis.Number(object.displayValue) : 0,
            displayLabel: isSet(object.displayLabel) ? globalThis.String(object.displayLabel) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== 0) {
            obj.value = Math.round(message.value);
        }
        if (message.label !== "") {
            obj.label = message.label;
        }
        if (message.displayValue !== 0) {
            obj.displayValue = Math.round(message.displayValue);
        }
        if (message.displayLabel !== "") {
            obj.displayLabel = message.displayLabel;
        }
        return obj;
    },
    create(base) {
        return ConfigFieldOption.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConfigFieldOption();
        message.value = object.value ?? 0;
        message.label = object.label ?? "";
        message.displayValue = object.displayValue ?? 0;
        message.displayLabel = object.displayLabel ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
