// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: studio.proto
/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Request as Request2, Response as Response10 } from "./behaviors";
import { Request as Request7, Response as Response15 } from "./ble_profiles";
import { Notification as Notification19, Request as Request5, Response as Response13 } from "./combos";
import { Notification as Notification16, Request as Request1, Response as Response9 } from "./core";
import { Notification as Notification17, Request as Request3, Response as Response11 } from "./keymap";
import { Notification as Notification20, Request as Request6, Response as Response14 } from "./macros";
import { Response as Response8 } from "./meta";
import { Notification as Notification18, Request as Request4, Response as Response12 } from "./meteorite";
export const protobufPackage = "zmk.studio";
function createBaseRequest() {
    return {
        requestId: 0,
        core: undefined,
        behaviors: undefined,
        keymap: undefined,
        meteorite: undefined,
        combos: undefined,
        macros: undefined,
        bleProfiles: undefined,
    };
}
export const Request = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.requestId !== 0) {
            writer.uint32(8).uint32(message.requestId);
        }
        if (message.core !== undefined) {
            Request1.encode(message.core, writer.uint32(26).fork()).ldelim();
        }
        if (message.behaviors !== undefined) {
            Request2.encode(message.behaviors, writer.uint32(34).fork()).ldelim();
        }
        if (message.keymap !== undefined) {
            Request3.encode(message.keymap, writer.uint32(42).fork()).ldelim();
        }
        if (message.meteorite !== undefined) {
            Request4.encode(message.meteorite, writer.uint32(50).fork()).ldelim();
        }
        if (message.combos !== undefined) {
            Request5.encode(message.combos, writer.uint32(58).fork()).ldelim();
        }
        if (message.macros !== undefined) {
            Request6.encode(message.macros, writer.uint32(66).fork()).ldelim();
        }
        if (message.bleProfiles !== undefined) {
            Request7.encode(message.bleProfiles, writer.uint32(74).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.requestId = reader.uint32();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.core = Request1.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.behaviors = Request2.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.keymap = Request3.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.meteorite = Request4.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.combos = Request5.decode(reader, reader.uint32());
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.macros = Request6.decode(reader, reader.uint32());
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.bleProfiles = Request7.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            requestId: isSet(object.requestId) ? globalThis.Number(object.requestId) : 0,
            core: isSet(object.core) ? Request1.fromJSON(object.core) : undefined,
            behaviors: isSet(object.behaviors) ? Request2.fromJSON(object.behaviors) : undefined,
            keymap: isSet(object.keymap) ? Request3.fromJSON(object.keymap) : undefined,
            meteorite: isSet(object.meteorite) ? Request4.fromJSON(object.meteorite) : undefined,
            combos: isSet(object.combos) ? Request5.fromJSON(object.combos) : undefined,
            macros: isSet(object.macros) ? Request6.fromJSON(object.macros) : undefined,
            bleProfiles: isSet(object.bleProfiles) ? Request7.fromJSON(object.bleProfiles) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.requestId !== 0) {
            obj.requestId = Math.round(message.requestId);
        }
        if (message.core !== undefined) {
            obj.core = Request1.toJSON(message.core);
        }
        if (message.behaviors !== undefined) {
            obj.behaviors = Request2.toJSON(message.behaviors);
        }
        if (message.keymap !== undefined) {
            obj.keymap = Request3.toJSON(message.keymap);
        }
        if (message.meteorite !== undefined) {
            obj.meteorite = Request4.toJSON(message.meteorite);
        }
        if (message.combos !== undefined) {
            obj.combos = Request5.toJSON(message.combos);
        }
        if (message.macros !== undefined) {
            obj.macros = Request6.toJSON(message.macros);
        }
        if (message.bleProfiles !== undefined) {
            obj.bleProfiles = Request7.toJSON(message.bleProfiles);
        }
        return obj;
    },
    create(base) {
        return Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.requestId = object.requestId ?? 0;
        message.core = (object.core !== undefined && object.core !== null) ? Request1.fromPartial(object.core) : undefined;
        message.behaviors = (object.behaviors !== undefined && object.behaviors !== null)
            ? Request2.fromPartial(object.behaviors)
            : undefined;
        message.keymap = (object.keymap !== undefined && object.keymap !== null)
            ? Request3.fromPartial(object.keymap)
            : undefined;
        message.meteorite = (object.meteorite !== undefined && object.meteorite !== null)
            ? Request4.fromPartial(object.meteorite)
            : undefined;
        message.combos = (object.combos !== undefined && object.combos !== null)
            ? Request5.fromPartial(object.combos)
            : undefined;
        message.macros = (object.macros !== undefined && object.macros !== null)
            ? Request6.fromPartial(object.macros)
            : undefined;
        message.bleProfiles = (object.bleProfiles !== undefined && object.bleProfiles !== null)
            ? Request7.fromPartial(object.bleProfiles)
            : undefined;
        return message;
    },
};
function createBaseResponse() {
    return { requestResponse: undefined, notification: undefined };
}
export const Response = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.requestResponse !== undefined) {
            RequestResponse.encode(message.requestResponse, writer.uint32(10).fork()).ldelim();
        }
        if (message.notification !== undefined) {
            Notification.encode(message.notification, writer.uint32(18).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.requestResponse = RequestResponse.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.notification = Notification.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            requestResponse: isSet(object.requestResponse) ? RequestResponse.fromJSON(object.requestResponse) : undefined,
            notification: isSet(object.notification) ? Notification.fromJSON(object.notification) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.requestResponse !== undefined) {
            obj.requestResponse = RequestResponse.toJSON(message.requestResponse);
        }
        if (message.notification !== undefined) {
            obj.notification = Notification.toJSON(message.notification);
        }
        return obj;
    },
    create(base) {
        return Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.requestResponse = (object.requestResponse !== undefined && object.requestResponse !== null)
            ? RequestResponse.fromPartial(object.requestResponse)
            : undefined;
        message.notification = (object.notification !== undefined && object.notification !== null)
            ? Notification.fromPartial(object.notification)
            : undefined;
        return message;
    },
};
function createBaseRequestResponse() {
    return {
        requestId: 0,
        meta: undefined,
        core: undefined,
        behaviors: undefined,
        keymap: undefined,
        meteorite: undefined,
        combos: undefined,
        macros: undefined,
        bleProfiles: undefined,
    };
}
export const RequestResponse = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.requestId !== 0) {
            writer.uint32(8).uint32(message.requestId);
        }
        if (message.meta !== undefined) {
            Response8.encode(message.meta, writer.uint32(18).fork()).ldelim();
        }
        if (message.core !== undefined) {
            Response9.encode(message.core, writer.uint32(26).fork()).ldelim();
        }
        if (message.behaviors !== undefined) {
            Response10.encode(message.behaviors, writer.uint32(34).fork()).ldelim();
        }
        if (message.keymap !== undefined) {
            Response11.encode(message.keymap, writer.uint32(42).fork()).ldelim();
        }
        if (message.meteorite !== undefined) {
            Response12.encode(message.meteorite, writer.uint32(50).fork()).ldelim();
        }
        if (message.combos !== undefined) {
            Response13.encode(message.combos, writer.uint32(58).fork()).ldelim();
        }
        if (message.macros !== undefined) {
            Response14.encode(message.macros, writer.uint32(66).fork()).ldelim();
        }
        if (message.bleProfiles !== undefined) {
            Response15.encode(message.bleProfiles, writer.uint32(74).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequestResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.requestId = reader.uint32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.meta = Response8.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.core = Response9.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.behaviors = Response10.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.keymap = Response11.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.meteorite = Response12.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.combos = Response13.decode(reader, reader.uint32());
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.macros = Response14.decode(reader, reader.uint32());
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.bleProfiles = Response15.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            requestId: isSet(object.requestId) ? globalThis.Number(object.requestId) : 0,
            meta: isSet(object.meta) ? Response8.fromJSON(object.meta) : undefined,
            core: isSet(object.core) ? Response9.fromJSON(object.core) : undefined,
            behaviors: isSet(object.behaviors) ? Response10.fromJSON(object.behaviors) : undefined,
            keymap: isSet(object.keymap) ? Response11.fromJSON(object.keymap) : undefined,
            meteorite: isSet(object.meteorite) ? Response12.fromJSON(object.meteorite) : undefined,
            combos: isSet(object.combos) ? Response13.fromJSON(object.combos) : undefined,
            macros: isSet(object.macros) ? Response14.fromJSON(object.macros) : undefined,
            bleProfiles: isSet(object.bleProfiles) ? Response15.fromJSON(object.bleProfiles) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.requestId !== 0) {
            obj.requestId = Math.round(message.requestId);
        }
        if (message.meta !== undefined) {
            obj.meta = Response8.toJSON(message.meta);
        }
        if (message.core !== undefined) {
            obj.core = Response9.toJSON(message.core);
        }
        if (message.behaviors !== undefined) {
            obj.behaviors = Response10.toJSON(message.behaviors);
        }
        if (message.keymap !== undefined) {
            obj.keymap = Response11.toJSON(message.keymap);
        }
        if (message.meteorite !== undefined) {
            obj.meteorite = Response12.toJSON(message.meteorite);
        }
        if (message.combos !== undefined) {
            obj.combos = Response13.toJSON(message.combos);
        }
        if (message.macros !== undefined) {
            obj.macros = Response14.toJSON(message.macros);
        }
        if (message.bleProfiles !== undefined) {
            obj.bleProfiles = Response15.toJSON(message.bleProfiles);
        }
        return obj;
    },
    create(base) {
        return RequestResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequestResponse();
        message.requestId = object.requestId ?? 0;
        message.meta = (object.meta !== undefined && object.meta !== null) ? Response8.fromPartial(object.meta) : undefined;
        message.core = (object.core !== undefined && object.core !== null) ? Response9.fromPartial(object.core) : undefined;
        message.behaviors = (object.behaviors !== undefined && object.behaviors !== null)
            ? Response10.fromPartial(object.behaviors)
            : undefined;
        message.keymap = (object.keymap !== undefined && object.keymap !== null)
            ? Response11.fromPartial(object.keymap)
            : undefined;
        message.meteorite = (object.meteorite !== undefined && object.meteorite !== null)
            ? Response12.fromPartial(object.meteorite)
            : undefined;
        message.combos = (object.combos !== undefined && object.combos !== null)
            ? Response13.fromPartial(object.combos)
            : undefined;
        message.macros = (object.macros !== undefined && object.macros !== null)
            ? Response14.fromPartial(object.macros)
            : undefined;
        message.bleProfiles = (object.bleProfiles !== undefined && object.bleProfiles !== null)
            ? Response15.fromPartial(object.bleProfiles)
            : undefined;
        return message;
    },
};
function createBaseNotification() {
    return { core: undefined, keymap: undefined, meteorite: undefined, combos: undefined, macros: undefined };
}
export const Notification = {
    encode(message, writer = _m0.Writer.create()) {
        if (message.core !== undefined) {
            Notification16.encode(message.core, writer.uint32(18).fork()).ldelim();
        }
        if (message.keymap !== undefined) {
            Notification17.encode(message.keymap, writer.uint32(42).fork()).ldelim();
        }
        if (message.meteorite !== undefined) {
            Notification18.encode(message.meteorite, writer.uint32(50).fork()).ldelim();
        }
        if (message.combos !== undefined) {
            Notification19.encode(message.combos, writer.uint32(58).fork()).ldelim();
        }
        if (message.macros !== undefined) {
            Notification20.encode(message.macros, writer.uint32(66).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNotification();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.core = Notification16.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.keymap = Notification17.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.meteorite = Notification18.decode(reader, reader.uint32());
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.combos = Notification19.decode(reader, reader.uint32());
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.macros = Notification20.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            core: isSet(object.core) ? Notification16.fromJSON(object.core) : undefined,
            keymap: isSet(object.keymap) ? Notification17.fromJSON(object.keymap) : undefined,
            meteorite: isSet(object.meteorite) ? Notification18.fromJSON(object.meteorite) : undefined,
            combos: isSet(object.combos) ? Notification19.fromJSON(object.combos) : undefined,
            macros: isSet(object.macros) ? Notification20.fromJSON(object.macros) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.core !== undefined) {
            obj.core = Notification16.toJSON(message.core);
        }
        if (message.keymap !== undefined) {
            obj.keymap = Notification17.toJSON(message.keymap);
        }
        if (message.meteorite !== undefined) {
            obj.meteorite = Notification18.toJSON(message.meteorite);
        }
        if (message.combos !== undefined) {
            obj.combos = Notification19.toJSON(message.combos);
        }
        if (message.macros !== undefined) {
            obj.macros = Notification20.toJSON(message.macros);
        }
        return obj;
    },
    create(base) {
        return Notification.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNotification();
        message.core = (object.core !== undefined && object.core !== null)
            ? Notification16.fromPartial(object.core)
            : undefined;
        message.keymap = (object.keymap !== undefined && object.keymap !== null)
            ? Notification17.fromPartial(object.keymap)
            : undefined;
        message.meteorite = (object.meteorite !== undefined && object.meteorite !== null)
            ? Notification18.fromPartial(object.meteorite)
            : undefined;
        message.combos = (object.combos !== undefined && object.combos !== null)
            ? Notification19.fromPartial(object.combos)
            : undefined;
        message.macros = (object.macros !== undefined && object.macros !== null)
            ? Notification20.fromPartial(object.macros)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
